<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect
 
/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
			$price = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
			$price = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
			$price = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
			$price = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = false;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
			$price = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = false;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
			$price = true;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
			$price = false;
        }
    break;

    default:
        $exist = null;
}
$meigee_helper = $this->helper('\Meigee\Barbour\Helper\BarbourGeneral');
$name_align = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'product_name_aligment');
$rand = rand(100, 100000);
?>

<?php if ($exist) :?>

        <?php if ($type == 'crosssell' || $type == 'crosssell-rule') : ?>
            <div class="crosssell-wrapper">
        <?php endif; ?>
            <?php if ($type == 'related' || $type == 'upsell') : ?>
                <?php if ($type == 'related') : ?>
                    <div class="block accordion-item <?php echo $block->escapeHtmlAttr($class); ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @noEscape */ echo $shuffle; ?>">
                <?php else: ?>
                    <div class="block accordion-item <?php echo $block->escapeHtmlAttr($class); ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @noEscape */ echo $shuffle; ?>">
                <?php endif; ?>
            <?php else: ?>
                <div class="block accordion-item <?php echo $block->escapeHtmlAttr($class); ?>">
            <?php endif; ?>
            <div class="block-title title accordion-title">
                <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
                <span class="icon-more"><i class="icon-plus meigee-plus"></i><i class="icon-minus meigee-minus"></i></span>
            </div>
            <div class="block-content content accordion-content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
                <?php if ($type == 'related' && $canItemsAddToCart) : ?>
                <div class="block-actions">
                    <?php echo $block->escapeHtml(__('Check items to add to the cart or')) ?>
                    <span class="action select" role="button"><span><?php echo $block->escapeHtml(__('select all')) ?></span></span>
                </div>
                <?php endif; ?>
                <div class="products wrapper grid products-grid clearfix products-<?php echo $block->escapeHtmlAttr($type); ?>">
                    <ol class="products list items row product-items clearfix">
                        <?php foreach ($items as $_item): ?>
                        <?php $available = ''; ?>
                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related') : ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <?php $available = 'related-available'; ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php if ($type == 'related' || $type == 'upsell') : ?>
                            <li class="item product product-item" style="display: none;">
                        <?php else: ?>
                            <li class="item product product-item">
                        <?php endif; ?>
							<div class="product-item-info <?php /* @noEscape */ echo $available; ?><?php echo !$_item->isAvailable() ? ' sold-out' : ''; ?>">
								<div class="image-wrapper">
									<?php /* @noEscape */ echo '<!-- ' . $image . '-->' ?>
									<a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
										<?php echo $block->getImage($_item, $image)->toHtml(); ?>
									</a>
									<?php if (!$_item->isAvailable()) : ?>
										<div class="sold-out-label">
											<span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
										</div>
									<?php endif; ?>
								</div>
								<div class="product details product-item-details">
									<strong class="product name product-item-name <?php echo $name_align; ?>"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>">
										<?php echo $block->escapeHtml($_item->getName()) ?></a>
									</strong>
									
									<?php if($price) {
											/* @noEscape */echo $block->getProductPrice($_item);
										}
									?>

										<?php if ($templateType) { ?>
											<?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
										<?php } ?>

										<?php echo str_replace('grid', 'grid-'.$rand.'-product-'.$_item->getId().'', $_item->getProductPriceHtml($_item, $type)); ?>
										<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related') { ?>
											<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
											<?php if (!$_item->getRequiredOptions()) { ?>
												<div class="field choice related">
													<input type="checkbox" class="checkbox related" id="related-checkbox<?php echo $block->escapeHtmlAttr($_item->getId()) ?>" name="related_products[]" value="<?php echo $block->escapeHtmlAttr($_item->getId()) ?>" />
													<label class="label" for="related-checkbox<?php echo $block->escapeHtmlAttr($_item->getId()) ?>"><span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span></label>
												</div>
											<?php } ?>
										<?php } ?>

										<?php if ($showCart) { ?>
											<?php if ($_item->isSaleable()) { ?>
												<?php if ($_item->isSaleable()) { ?>
													<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) { ?>
														<button class="btn btn-default btn-cart" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
															<i class="meigee-cart"></i>
															<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
														</button>
													<?php }else{ ?>
														<?php $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
														$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
														?>
														<button class="btn btn-default btn-cart"
														data-post='<?php /* @noEscape */ echo $postData; ?>'
														type="button" title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')) ?>">
														<i class="meigee-cart"></i>
														<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
													</button>
													<?php } ?>
												<?php } ?>
											<?php } ?>
										<?php } ?>
										<?php if ($showAddTo) : ?>
											<div class="add-to-links" data-role="add-to-links">
												<?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
													<?php echo $addToBlock->setProduct($_item)->getChildHtml(); ?>
												<?php endif; ?>
											</div>
										<?php endif; ?>
									</div>
								</div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
        <?php if ($type == 'crosssell' || $type == 'crosssell-rule') : ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif;?>
