<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Framework\View\Element\Html\Link
 */
?>
<?php if (!$block->getIsDisabled()): ?>
<li>
    <a href="<?php echo $block->escapeUrl($block->getHref())?>"
        <?php if ($title = $block->getTitle()):?> title="<?php echo $block->escapeHtmlAttr(__($title))?>"<?php endif;?>>
        <?php echo $block->escapeHtml(__($block->getLabel()))?>
    </a>
</li>
<?php endif; ?>
