<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
$productLabelHelper = $this->helper(Winestop\Custom\Helper\Data::class);
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) :?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'category_page_list';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    // $templateType =  \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;

    $meigee_helper = $this->helper('\Meigee\Barbour\Helper\BarbourGeneral');
    $lightbox_status = $meigee_helper->getCustomThemeOptionCnf('barbour_lightbox', 'lightbox_status');
    $lightbox_widget_status = $meigee_helper->getCustomThemeOptionCnf('barbour_lightbox', 'lightbox_home');
    $name_align = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'product_name_aligment');
    $stock_status = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'stock_status');
    $rand = rand(5, 1500);
    $quickview_status = $this->helper('WeltPixel\Quickview\Helper\Data')->getConfig('weltpixel_quickview/general/enable_product_listing');
    $quickview_btn = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'quickview_btn');

    $labels_type = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_type');
    $label_new = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_new');
    $label_sale = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_sale');
    $label_sale_percentage = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_sale_percentage');

    $image_hover_status = $meigee_helper->getCustomThemeOptionCnf('barbour_image_hover', 'image_hover_status');
    $image_hover_effect = $meigee_helper->getCustomThemeOptionCnf('barbour_image_hover', 'image_hover_type');

    $front_helper = $this->helper('\Meigee\Barbour\Helper\FrontHelper');

    $productsPerRow = $block->getProductsPerRow();

    switch($productsPerRow){
        case 1:
            $productsPerRow = 'one-column';
        break;
        case 2:
            $productsPerRow = 'two-columns';
        break;
        case 3:
            $productsPerRow = 'three-columns';
        break;
        case 4:
            $productsPerRow = 'four-columns';
        break;
        case 5:
            $productsPerRow = 'five-columns';
        break;
        case 6:
            $productsPerRow = 'six-columns';
        break;
    }
?>
    <div class="block widget block-products-list <?php /* @noEscape */ echo $mode; ?>">
        <?php if ($block->getTitle()) : ?>
        <div class="block-title">
            <strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong>
        </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @noEscape */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @noEscape */ echo $mode; ?> <?php /* @noEscape */ echo $mode .' '. $type; echo ' '.$productsPerRow; if($image_hover_status){echo $image_hover_effect ? ' hover-scale' : ' hover-simple';} ?>">
                <ol class="product-items product-slider-grid row owl-carousel owl-theme">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php if ($_item->getTypeID() != 'mpgiftcard' && $_item->isAvailable()) { ?>
                            <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                            <div class="product-item-info<?php echo !$_item->getIsSalable() ? ' sold-out' : ''; ?>">
                                <div class="indent product-hover-1">
                                    <div class="image-wrapper">
                                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                            <?php
                                            $hoverImage = $image_hover_status ? $_item->getHoverImage() : false;
                                            $productImage = $block->getImage($_item, $image, array('data-hover-image'=>null, "loading"=>"lazy"));
                                            echo $productImage->toHtml();
                                            ?>
                                        </a>
                                        <?php
                                            if($front_helper->isProductNew($_item) || $front_helper->isProductSale($_item) || $front_helper->isProductOnlyLeft($_item)) {
                                                echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_item) && $front_helper->isProductSale($_item)) || ($front_helper->isProductNew($_item) && $front_helper->isProductOnlyLeft($_item)) ? ' two-items' : '').'">';
                                                    if ($front_helper->isProductOnlyLeft($_item) && $label_sale) {
                                                        echo $front_helper->isProductOnlyLeft($_item);
                                                    }
                                                    elseif($front_helper->getProductSalePercent($_item) && $label_sale) {
                                                        echo $front_helper->getProductSalePercent($_item);
                                                    } elseif ($front_helper->isProductSale($_item) && $label_sale) {
                                                        echo '<span class="label-sale">'.__('sale').'</span>';
                                                    }
                                                echo '</div>';
                                            }
                                        ?>
                                        <div class="hover-buttons">
                                            <?php if($lightbox_status && $lightbox_widget_status) { ?>
                                                <?php if ($_item->getData('thumbnail')) { ?>
                                                        <a href="<?php echo $this->getUrl() . 'pub/media/catalog/product/' .$_item->getData('thumbnail');  ?>" class="lightbox-button" data-toggle="lightbox" data-footer="<?php echo $block->escapeHtml($_item->getName()); ?>" title="<?php echo __('Lightbox'); ?>">
                                                    <?php } else {  ?>
                                                        <a href="<?php echo $productImage->getImageUrl();  ?>" class="lightbox-button" data-toggle="lightbox" data-footer="<?php echo $block->escapeHtml($_item->getName()); ?>" title="<?php echo __('Lightbox'); ?>">
                                                    <?php } ?>                                                
                                                    <i class="meigee-zoom"></i>
                                                </a>
                                            <?php } ?>
                                            <?php if ($showWishlist || $showCompare) : ?>
                                                <div class="add-to-links" data-role="add-to-links">
                                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                        <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                        <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                            <i class="meigee-chart"></i>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if($quickview_btn && $quickview_status) { ?>
                                            <a href="javascript: void(0);" data-quickview-url="<?php echo $block->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_item->getEntityId()); ?>" class="weltpixel-quickview"><i class="meigee-fa-eye"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
                                            <?php } ?>
                                            <?php if($showCart){ ?>
                                                <div class="product-action-wrapper">
                                                    <?php if ($showCart): ?>
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                <button class="btn btn-default btn-cart action tocart"
                                                                        data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <i class="meigee-cart"></i>
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php
                                                                    $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="btn btn-default btn-cart"
                                                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <i class="meigee-cart"></i>
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php }?>
                                        </div>
                                        <?php if (!$_item->getIsSalable()) : ?>
                                            <div class="sold-out-label">
                                                <span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                    <div class="product-item-details">
                                        <h4 class="product-item-name <?php echo $name_align; ?>">
                                            <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                               class="product-item-link">
                                                <?= $block->escapeHtml($_item->getName()) ?>
                                            </a>
                                        </h4>

                                        <?= $block->getProductDetailsHtml($_item) ?>

                                        <?php if($stock_status != 4 && $stock_status != 2) {
                                            if ($_item->getIsSalable()) : ?>
                                                <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                            <?php endif;
                                        } ?>
                                        <?php
                                        //labels start
                                        $specialArr = [];
                                        $newProduct = $productLabelHelper->isNewArrival($_item);
                                            if($newProduct){
                                                $specialArr['New Arrival']=$newProduct;
                                            }
                                        ?>
                                        <?php
                                        $specialAssignment = $productLabelHelper->getSpecialAttribute($_item);

                                        if ($specialAssignment) {
                                            foreach ($specialAssignment as $key => $assignValue) {
                                                if($newProduct) {
                                                    if ($assignValue) {
                                                        $className = $productLabelHelper->getClassName($assignValue); 
                                                        $specialArr[$className]=$assignValue;
                                                        break;
                                                    }
                                                }else{
                                                    if($key>1){
                                                        break;
                                                    }
                                                    if ($assignValue) {
                                                        $className = $productLabelHelper->getClassName($assignValue); 
                                                        $specialArr[$className]=$assignValue;
                                                    }
                                                }
                                            }
                                        }
                                        //if(count($specialArr)):?>
                                            <div class="labels">
                                                <?php foreach ($specialArr as $className => $_assignValue) :?>
                                                    <label for="<?=($className=='New Arrival')?'newarrival':'specialattribute'?>">
                                                        <span class="<?=($className=='New Arrival')?'newarrival':$className ?>">
                                                            <img class="white-icon" src="<?php echo $this->getViewFileUrl('images/'.$className.'.png'); ?>" alt="<?php $_assignValue ?>" height="auto">
                                                        </span>
                                                    </label>
                                                <?php endforeach;?>
                                            </div>
                                        <?php //endif;?>
                                        <?php //labels end ?>
                                        <?php if($block->getProductPriceHtml($_item, $type)) { ?>
                                            <?php echo str_replace('grid', 'grid-'.$rand.'-product-'.$_item->getId().'', $block->getProductPriceHtml($_item, $type)); ?>
                                        <?php } ?>
                                        <div class="product_member_price">
                                        <?php if ($_item->getData('member_price')) { ?>
                                            <?php
                                            $member_price = $_item->getData('member_price');
                                            $member_price = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($member_price,true,false);
                                            $block_obj_custom = $this->getLayout()->createBlock('Winestop\Custom\Block\Customdata');
                                            $is_login = $block_obj_custom->isCustomerLoggedIn();
                                            ?>
                                            <?php if ($is_login) { ?>
                                                <!-- <div class="product_member_price"> -->
                                                    <div class="price_label">
                                                        <span>Member Price: </span>
                                                        <span><?php echo $member_price; ?></span>
                                                    </div>
                                                <!-- </div> -->
                                            <?php }else{ ?>
                                                <!-- <div class="product_member_price"> -->
                                                    <div class="price_label not_login">
                                                        <a href="/customer/account/login/"><span>Member Price</span></a>
                                                    </div>
                                                <!-- </div> -->
                                            <?php } ?>
                                        <?php } ?>
                                        </div>
                                        <?php
                                            $all_wine_rating = array("ag_rating", "bh_rating", "cg_rating","gr_rating","jd_rating",
                                                          "jh_rating","js_rating","pr_rating","rp_rating","st_rating",
                                                          "wa_rating","we_rating","wns_rating","wn_rating","ws_rating","d_rating","sk_rating","jg_rating");
                                            $cnt = 0;
                                        ?>
                                        <div class="wine_rating_block">
                                            <?php foreach($all_wine_rating as $Wine_rating) { ?>
                                                <?php if (null !== $_item->getCustomAttribute($Wine_rating) && null !== $_item->getCustomAttribute($Wine_rating."_low")) {
                                                            $rating_label = substr($Wine_rating, 0, strpos($Wine_rating, '_'));
                                                            if ($rating_label == 'wns') {
                                                                $rating_label = 'w&s';
                                                            }
                                                            if ($rating_label == 'ag') {
                                                                $rating_label = 'V';
                                                            }
                                                         ?>
                                                                <?php if ($cnt == 0) { ?>
                                                                    <div class="rating_label">
                                                                        <span>Rating(s)</span>
                                                                    </div>
                                                                    <?php $cnt++; ?>
                                                                <?php } ?>
                                                                <div class="wine_rate_box_combo wine_rate_box">
                                                                    <a href="/rating-guide">
                                                                    <span><?php echo strtoupper($rating_label); ?></span>
                                                                    <span><?php echo $_item->getAttributeText($Wine_rating."_low") . " - "; ?></span>
                                                                    <span><?php echo $_item->getAttributeText($Wine_rating); ?></span>
                                                                    </a>
                                                                </div>
                                                <?php } else { ?>
                                                            <?php if (null !== $_item->getCustomAttribute($Wine_rating)) { ?>
                                                                <?php $rating_label = substr($Wine_rating, 0, strpos($Wine_rating, '_'));
                                                                    if ($rating_label == 'wns') {
                                                                        $rating_label = 'w&s';
                                                                    }
                                                                    if ($rating_label == 'ag') {
                                                                        $rating_label = 'V';
                                                                    }
                                                                 ?>
                                                                <?php if ($cnt == 0) { ?>
                                                                    <div class="rating_label">
                                                                        <span>Rating(s)</span>
                                                                    </div>
                                                                    <?php $cnt++; ?>
                                                                <?php } ?>
                                                                    <div class="wine_rate_box">
                                                                        <a href="/rating-guide">
                                                                        <span><?php echo $_item->getAttributeText($Wine_rating); ?></span>
                                                                        <span><?php echo strtoupper($rating_label); ?></span>
                                                                        </a>
                                                                    </div>
                                                            <?php } ?>
                                                                <?php if (null !== $_item->getCustomAttribute($Wine_rating."_low")) { ?>
                                                                    <?php $rating_label = substr($Wine_rating."_low", 0, strpos($Wine_rating."_low", '_'));
                                                                        if ($rating_label == 'wns') {
                                                                           $rating_label = 'w&s';
                                                                        }
                                                                        if ($rating_label == 'ag') {
                                                                            $rating_label = 'V';
                                                                        }
                                                                     ?>
                                                                    <?php if ($cnt == 0) { ?>
                                                                        <div class="rating_label">
                                                                            <span>Rating(s)</span>
                                                                        </div>
                                                                        <?php $cnt++; ?>
                                                                    <?php } ?>
                                                                    <div class="wine_rate_box">
                                                                        <a href="/rating-guide">
                                                                        <span><?php echo $_item->getAttributeText($Wine_rating."_low"); ?></span>
                                                                        <span><?php echo strtoupper($rating_label); ?></span>
                                                                        </a>
                                                                    </div>
                                                                <?php } ?>
                                                <?php } ?>
                                            <?php } ?>
                                        </div>
                                        <div class="availableqty">
                                                <?php
                                                 $productId = $_item->getId();
                                                 $qty = $productLabelHelper->getStockItem($productId);
                                                ?>
                                                <?php if ($qty>0): ?>
                                                <label for="availableqty">Inventory : </label>
                                                <?php if ($qty > 24) : ?>
                                                <span><?php echo "24+"; ?></span>
                                                <?php else: ?>
                                                <span><?= $qty ?></span>
                                                <?php endif; ?>
                                                <?php else: ?>
                                                <label for="outofstock" class="outofstock">Inventory : </label>
                                                <span class="outofstock"><?php echo "Out of Stock"; ?></span>
                                                <?php endif;?>
                                        </div>
                                        <?php if ($_item->isSaleable()){ ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                                <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?php echo $block->escapeUrl($postParams['action']); ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                    <button type="submit"
                                                            title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
                                                            class="action tocart btn btn-default btn-cart">
                                                        <i class="meigee-cart"></i>
                                                        <span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
                                                    </button>
                                                </form>
                                    <?php } ?>
                                        <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_item)->toHtml(); ?>
                                    </div>
                                </div>
                            </div>
                            <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php } ?>
                    <?php endforeach ?>
                </ol>
            </div>
             <script type="text/javascript">
                    require(["jquery"], function(jQuery)
                    {
                        require(["MeigeeCarousel"], function(owlCarousel)
                        {
                            jQuery('.product-slider-grid').owlCarousel({
                                margin: 0,
                                nav:true,
                                responsive:{
                                    0:{
                                        items:1
                                    },
                                    480:{
                                        items:2
                                    },
                                    767:{
                                        items:3
                                    },
                                    992:{
                                        items:2
                                    },
                                    1199:{
                                        items:2
                                    },
                                    1331:{
                                        items:3
                                    }
                                },
                                smartSpeed: 500,
                                dots: false,
                                loop: true,
                                nav: true
                            });
                        });
                      });
                </script>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>


