<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View */?>
<?php $_product = $block->getProduct() ?>
<?php $status = $_product->getQuantityAndStockStatus(); ?>
 <?php if ($status['is_in_stock'] != 1): ?>     
     <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
         <span><?php /* @escapeNotVerified */ echo __('Out of Stock') ?></span>
     </div>
 <?php endif; ?>

