l<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<?php /*
<div class="block newsletter">
    <div class="title"><strong><?php echo $block->escapeHtml(__('Newsletter')); ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php echo $block->escapeUrl($block->getFormActionUrl()); ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-content-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter-content"><span><?php echo $block->escapeHtml(__('Sign Up And Get Regular Updates On Offers And Promotions. Cheers!')) ?></span></label>
                <div class="input-wrapper">
                    <input class="form-control" name="email" type="email" id="newsletter-content"
                                placeholder="<?php echo $block->escapeHtml(__('Your Email Address')) ?>"
                                onfocus="this.placeholder = ''"
                                onblur="this.placeholder = 'Enter your email'"
								data-mage-init='{"mage/trim-input":{}}'
                                data-validate="{required:true, 'validate-email':true}"/>
                    <button class="action subscribe btn btn-primary primary type-2" title="<?php echo $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit" aria-label="Subscribe">
                        <span><?php echo $block->escapeHtml(__('Subscribe')) ?></span><i class="meigee-right-arrow-key"></i>
                    </button>

                </div>
            </div>
        </form>
    </div>
</div>
*/ ?>
<!-- Begin Constant Contact Inline Form Code -->
<div class="ctct-inline-form" data-form-id="fcbbac24-bacb-4a8d-94e1-6fae304b3f06"></div>
<!-- End Constant Contact Inline Form Code -->
