<div class="header-wrapper">
	<header class="page-header cart-header">
		<div class="middle-block">
			<div class="container">
				<div class="middle-block-inner clearfix">
					<div class="row">
						<div class="col-md-4 col-sm-12 left-block">
							<div class="panel header"><a class="action skip contentarea" href="#contentarea"><span>Skip to Content</span></a>
								<?php echo $this->getChildHtml("meigee.logo"); ?>
							</div>								
						</div>
						<div class="col-md-4 col-sm-12">
								<?php echo $this->getChildHtml("page.main.title"); ?>							
						</div>
						<div class="col-md-4 col-sm-2 right-block">						
							<?php echo $this->getChildHtml("options.wrapper"); ?>							
						</div>
					</div>
				</div>
			</div>
		</div>
    	<?php echo $this->getChildHtml("bgslider"); ?>
  </header>
  <?php echo $this->getChildHtml("meigee_sticky_header"); ?>
</div>