<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtml($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else :?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else :?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) :?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()) :?>
                    <?php foreach ($messages as $message) :?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) :?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <?php if ($canApplyMsrp) :?>
            <td class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else :?>
            <td class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
            <div class="field qty">
                <div class="control qty">
                    <div class="quantity-wrapper clearfix">
                        <div class="field qty">
                            <label class="label" for="qty"><span><?php echo $block->escapeHtml(__('Qty')) ?></span></label>
                            <div class="control clearfix">
                                <div class="quantity-decrease" onclick="qtyDown<?php echo $_item->getId(); ?>()"><i class="meigee-minus"></i></div>
                                <input id="cart-<?php echo $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                                       name="cart[<?php echo $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                       data-cart-item-id="<?php echo $block->escapeHtmlAttr($_item->getSku()); ?>"
                                       value="<?php echo $block->escapeHtmlAttr($block->getQty()) ?>"
                                       type="text"
                                       size="4"
                                       title="<?php echo $block->escapeHtmlAttr(__('Qty')); ?>"
                                       class="input-text qty cart-qty"
                                       maxlength="12"
                                       data-validate="{required:true,'validate-greater-than-zero':true}"
                                       data-role="cart-item-qty"/>
                                <div class="quantity-increase" onclick="qtyUp<?php echo $_item->getId(); ?>()"><i class="meigee-plus"></i></div>
                            </div>
                            <script type="text/javascript">
                                function qtyDown<?php echo $_item->getId(); ?>(){
                                    qty_el = document.getElementById('cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty');
                                    qty = qty_el.value;
                                    if( !isNaN( qty ) && qty > 1 ){
                                        qty_el.value--;
                                        document.getElementById('<?php echo 'qty-label-'.$_item->getId(); ?>').textContent = parseInt(qty_el.value);
                                    }
                                    return false;
                                }
                                function qtyUp<?php echo $_item->getId(); ?>(){
                                    qty_el = document.getElementById('cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty');
                                    qty = qty_el.value;
                                    if( !isNaN( qty )) {
                                        qty_el.value++;
                                        document.getElementById('<?php echo 'qty-label-'.$_item->getId(); ?>').textContent = parseInt(qty_el.value);
                                    }
                                    return false;
                                }
                                document.getElementById('cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty')
                                .addEventListener('keyup', function(event) {
                                    qty_el = document.getElementById('cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty');
                                    if( !isNaN( qty )) {
                                        document.getElementById('<?php echo 'qty-label-'.$_item->getId(); ?>').textContent = parseInt(qty_el.value);
                                    }
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp) :?>
                <span class="cart msrp subtotal">--</span>
            <?php else :?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
        <td class="col item_action">
            <div class="cart-actions">                
                    <?php
                        $remove_block = $block->getLayout()->createBlock('\Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove');
                        $edit_block = $block->getLayout()->createBlock('\Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit');
                    ?>
                    <?php if ($edit_block->setItem($_item)->isProductVisibleInSiteVisibility()) : ?>
                        <a class="action actmeigee-pencil"
                           href="<?php /* @escapeNotVerified */ echo $edit_block->setItem($_item)->getConfigureUrl() ?>"
                           title="<?php echo $block->escapeHtml(__('Edit item parameters')); ?>">
                            <i class="meigee-pencil"></i>
                       </a>
                    <?php endif ?>
                    <a href="#"
                       title="<?php echo $block->escapeHtml(__('Remove item')); ?>"
                       class="action action-delete"
                       data-post='<?php /* @escapeNotVerified */ echo $remove_block->setItem($_item)->getDeletePostJson($_item); ?>'>
                            <i class="meigee-x"></i>
                    </a>
            </div>
        </td>
    </tr>   
</tbody>
<script type="text/javascript">
    var qty_el = document.getElementById('qty');
    var qty = qty_el.value;            
    function qtyDown(){
        var qty_el = document.getElementById('qty');
        var qty = qty_el.value;               
        if( !isNaN( qty ) && qty > 0 ){
            qty_el.value--;
        }
        return false;
    }
    function qtyUp(){
        var qty_el = document.getElementById('qty');
        var qty = qty_el.value;
        if( !isNaN( qty )) {
            qty_el.value++;
        }               
        return false;
    }
</script>