<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */

$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
$mainImage->getData('medium_image_url') :
$helper->getDefaultPlaceholderUrl('image');

$meigee_helper = $this->helper('\Meigee\Barbour\Helper\BarbourGeneral');
$moreViewsType = $meigee_helper->getCustomThemeOptionCnf('barbour_product_view', 'product_more_views_type');

switch ($moreViewsType) {
	case 'list':
		$moreViewsTypeClassname = 'no-slider';
	break;
	case 'horizontal_slider':
		$moreViewsTypeClassname = 'more-views-horizontal-slider';
	break;
	case 'vertical_type_1':
		$moreViewsTypeClassname = 'more-views-vertical-slider type-1 ';
	break;
	case 'vertical_type_2':
		$moreViewsTypeClassname = 'more-views-vertical-slider type-2';
	break;
	case 'large':
		$moreViewsTypeClassname = 'more-views-large';
	break;
	default:
		$moreViewsTypeClassname = 'more-views-horizontal-slider';
	break;
}
?>
<div class="gallery-placeholder _block-content-loading <?php echo $moreViewsTypeClassname; ?><?php echo count($block->getGalleryImages()) == 1 ? ' single-image' : ''; ?>" data-gallery-role="gallery-placeholder">
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />
</div>
<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "nav": "<?php
                    //Special case for gallery/nav which can be the string "thumbs/false/dots"
                    if (is_bool($block->getVar("gallery/nav"))) {
                        echo $block->getVar("gallery/nav") ? 'true' : 'false';
                    } else {
                        echo $block->escapeHtml($block->getVar("gallery/nav"));
                    }
                    ?>",
                    "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/loop") ? 'true' : 'false' ?>,
                    "keyboard": <?= /* @escapeNotVerified */ $block->getVar("gallery/keyboard") ? 'true' : 'false' ?>,
                    "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/arrows") ? 'true' : 'false' ?>,
                    "allowfullscreen": <?= /* @escapeNotVerified */ $block->getVar("gallery/allowfullscreen") ? 'true' : 'false' ?>,
                    "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/caption") ? 'true' : 'false' ?>,
					<?php if ($moreViewsType == "list"){ ?>
                        "thumbwidth": 124,
                        "thumbheight": 124,
                    <?php } elseif ($moreViewsType == "horizontal_slider"){ ?>
                        "thumbwidth": 104,
                        "thumbheight": 104,
                    <?php } elseif ($moreViewsType == "vertical_type_1" || $moreViewsType == 'vertical_type_2'){ ?>
                        "thumbwidth": 90,
                        "thumbheight": 90,
                    <?php } else { ?>
                        "thumbwidth": "<?= /* @escapeNotVerified */ (int)$block->escapeHtml($block->getImageAttribute('product_page_image_small', 'width')) ?>",
                        <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>
							"thumbheight": <?php echo $block->getImageAttribute('product_page_image_small', 'height') ?: (int)$block->escapeHtml($block->getImageAttribute('product_page_image_small', 'width')); ?>,
                        <?php endif; ?>
                    <?php } ?>
					<?php if ($moreViewsType == 'vertical_type_1'){ ?>
                        "height" : 700,
                        "width" : 810,
                    <?php } else { ?>
                        "width": "<?= (int)$block->escapeHtml($block->getImageAttribute('product_page_image_medium', 'width')) ?>",
                        <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
						"height": <?php echo $block->getImageAttribute('product_page_image_medium', 'height')
							?: (int)$block->escapeHtml($block->getImageAttribute('product_page_image_medium', 'width')); ?>,
						<?php endif; ?>
                    <?php } ?>
                    <?php if ($block->getVar("gallery/transition/duration")): ?>
                        "transitionduration": <?= (int)$block->escapeHtml($block->getVar("gallery/transition/duration")) ?>,
                    <?php endif; ?>
                    "transition": "<?= $block->escapeHtml($block->getVar("gallery/transition/effect")) ?>",
                    "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/navarrows") ? 'true' : 'false' ?>,
                    "navtype": "<?= $block->escapeHtml($block->getVar("gallery/navtype")) ?>",
					<?php if ($moreViewsType == 'vertical_type_1' || $moreViewsType == 'vertical_type_2'){ ?>
						"navdir": "vertical"
					<?php } else { ?>
						"navdir": "<?= $block->escapeHtml($block->getVar("gallery/navdir")) ?>"
					<?php } ?>
                },
                "fullscreen": {
                    "nav": "<?php
                        if (is_bool($block->getVar("gallery/fullscreen/nav"))) {
                            $fsOptionItems['nav'] = $block->getVar("gallery/fullscreen/nav") ? 'true' : 'false';
                        } else {
                            $fsOptionItems['nav'] = $block->escapeHtml($block->getVar("gallery/fullscreen/nav"));
                        }
                    ?>",
                    "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/loop") ? 'true' : 'false' ?>,
                    "navdir": "<?= $block->escapeHtml($block->getVar("gallery/fullscreen/navdir")) ?>",
					<?php if ($moreViewsType == "large"){ ?>
						"thumbwidth": 99,
						"thumbheight": 123,
					<?php } ?>
                    "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navarrows") ? 'true' : 'false' ?>,
                    "navtype": "<?= $block->escapeHtml($block->getVar("gallery/fullscreen/navtype")) ?>",
                    "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/arrows") ? 'true' : 'false' ?>,
                    "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/caption") ? 'true' : 'false' ?>,
                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>
                        "transitionduration": <?= (int)$block->escapeHtml($block->getVar("gallery/fullscreen/transition/duration")) ?>,
                    <?php endif; ?>
                    "transition": "<?= $block->escapeHtml($block->getVar("gallery/fullscreen/transition/effect")) ?>"
                },
                "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
<script>
    require(['jquery', 'mage/gallery/gallery'], function($, gallery){
        $('[data-gallery-role=gallery-placeholder]').on('gallery:loaded', function () {
            if($(window).width() > 767){
                $(this).on('fotorama:ready', function(){
                    setTimeout(function(){
                        var  api = $(this).data('gallery');
                        var offsetLeft = 0;
                        var mainOffset = $('#maincontent > .container').offset().left;
                        <?php if ($moreViewsType == 'vertical_type_2'){ ?>
                            var galleryOffset = $('.product.media .more-views-vertical-slider .fotorama__stage__shaft').offset().left;
                            var galleryWidth = $('.product.media .more-views-vertical-slider .fotorama__stage__shaft').width();
                            var setGalleryWidth = galleryWidth + galleryOffset - mainOffset;
                            $('.product.media .more-views-vertical-slider .fotorama__stage__shaft').css({
                                'width': setGalleryWidth
                            });
                            $('.product.media .more-views-vertical-slider .fotorama__stage').css({
                                'width': setGalleryWidth,
                            });
                        <?php } ?>
                        <?php if ($moreViewsType == 'vertical_type_1' || $moreViewsType == 'vertical_type_2'){ ?>
                            setTimeout(function(){
                                var galleryImgHeight = $('.more-views-vertical-slider .fotorama__stage .fotorama__img').height();
                                <?php if ($moreViewsType == 'vertical_type_1'){ ?>
                                    var navHeight = galleryImgHeight - 4;
                                <?php } else { ?>
                                    var navHeight = galleryImgHeight - $('.more-views-vertical-slider .fotorama__nav .fotorama__thumb__arr--left').height() - $('.more-views-vertical-slider .fotorama__nav .fotorama__thumb__arr--right').height() - 4;

                                <?php } ?>
                                var verticalThumbsHeight = $('.more-views-vertical-slider .fotorama__nav .fotorama__nav__shaft').height();
                                if (verticalThumbsHeight > galleryImgHeight) {
                                    $('.more-views-vertical-slider .fotorama__nav').css({
                                        'height' : navHeight
                                    });
                                }
                                console.log(navHeight);
                            }, 100);
                        <?php } ?>
                        <?php if ($moreViewsType == 'large'){ ?>
                            $('.product.media .gallery-placeholder .fotorama__nav--thumbs .fotorama__nav__frame').on('click', function(e) {
                                setTimeout(function(){
                                    api.fotorama.requestFullScreen();
                                }, 100);
                            })
                        <?php } ?>
                    }, 200);
                });
            }
        });
    });
</script>
