<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="add-review-link">
	<?php 
	$blockobj = $block->getLayout()->createBlock('Magento\Review\Block\Product\ReviewRenderer');
	$prodobj = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\View');
	$_product = $prodobj->getProduct();
	echo $blockobj->getReviewsSummaryHtml($_product,"sort",true);	
?>
	<a href="#product_tabs_reviews" class="add-review"><i class="meigee-pencil"></i><?php /* @escapeNotVerified */ echo __('Add Your Review') ?></a>
</div>
