<?php
	$helperobj = $this->helper('Winestop\Custom\Helper\Data');
	$only_wine_state = $helperobj->getConfig('custom/general/only_wine_state');
	$wsb_state = $helperobj->getConfig('custom/general/wsb_state');
	$only_wine_array = explode(",", $only_wine_state);
	$wsb_array = explode(",", $wsb_state);
	$all_option = $only_wine_state . ",". $wsb_state;
	$all_option_array = explode(",", $all_option);
	$state_code_name = [];
	sort($all_option_array);
	$product = $block->getProduct();
	$cat_id = '';
	foreach ($product->getCategoryCollection() as $cat) {
		if($cat['parent_id'] == '13') {
			$cat_id = $cat['parent_id'];
		}
	}
?>
<?php if ($cat_id == '13'): ?>
	<script type="text/javascript">
		require(['jquery', 'jquery/ui'], function($){
			jQuery(document).ready(function() {
			    var wsb_array = <?php echo json_encode($wsb_array); ?>;
			    var current_state = jQuery("#custom-delivery-checker").val();
			    var newData = sessionStorage.getItem("old_shipto_pdp");
			    	if (newData == null) {
			    		jQuery('.catalog-product-view .main-container .content-inner').css('display','block');
						jQuery('.catalog-product-view .ship_new_message').css('display','none');
			    	} else {
					   	if (jQuery.inArray(newData, wsb_array) > -1) {
							$('.catalog-product-view .main-container .content-inner').css('display','block');
							$('.catalog-product-view .ship_new_message').css('display','none');
					   	} else {
							$('.catalog-product-view .main-container .content-inner').css('display','none');
							$('.catalog-product-view .ship_new_message').css('display','block');
					   	}
				   	}
			});
     		document.getElementById('custom-delivery-checker').addEventListener('change', function () {
     			sessionStorage.setItem("old_shipto_pdp", this.value);
     			var wsb_array = <?php echo json_encode($wsb_array); ?>;
     			var current_state = this.value;
     			var newData = sessionStorage.getItem("old_shipto_pdp");
			    	if (newData == null) {
			    		jQuery('.catalog-product-view .main-container .content-inner').css('display','block');
						jQuery('.catalog-product-view .ship_new_message').css('display','none');
			    	} else {
					   	if (jQuery.inArray(newData, wsb_array) > -1) {
							$('.catalog-product-view .main-container .content-inner').css('display','block');
							$('.catalog-product-view .ship_new_message').css('display','none');
					   	} else {
							$('.catalog-product-view .main-container .content-inner').css('display','none');
							$('.catalog-product-view .ship_new_message').css('display','block');
					   	}
				   	}
    		});
 		});
</script>
<?php endif; ?>
<div class="ship_new_message" style="display: none;">
	<div class="message info empty">
		<div>
		<?php echo $block->escapeHtml(__('Sorry, we do not deliver spirits to your state')) ?>
		</div>
	</div>
</div>