<?php $buttons = $this->getButtons()?>
<?php $notLoginPage = $this->getCurrentPageRedirectUrl()?>
<?php if(!empty($buttons) && !$this->isCustomerLoggedIn()):?>
    <div class="block social-login-authentication-channel account-social-login">
        <div class="block-content">
            <div class="sociallogin-padding">
                <?php foreach ($buttons as $type => $data):?>
                    <div class="sociallogin-box">
                        <a class="sociallogin-button btn btn-block btn-social sl-<?= $type ?>"
                           rel="nofollow"
                           href="javascript:void(0);"
                           data-href="<?=$data['endpoint']?>">
                            <?php if ($type == 'google') : ?>
                                <span class="sociallogin-icon sl-<?=$type?> fa fa-google">Sign in with Google</span>
                            <?php elseif($type == 'fb') : ?>
                                <span class="sociallogin-icon sl-<?=$type?> fa fa-facebook">Sign in with Facebook</span>
                            <?php else: ?>
                                <span class="sociallogin-icon sl-<?=$type?>"></span>
                            <?php endif;  ?>
                        </a>
                    </div>
                <?php endforeach;?>
            </div>
        </div>
    </div>
    <script>
        if (window.socialloginButtons) {
            window.emailFormUrl = "<?=$this->getEmailFormUrl()?>";
            require(['sociallogin'], function(){
                sl.socialLoginClick();
                sl.sendEmailClick();
                sl.emailPopUp();
            });
        }
    </script>
<?php endif;?>