<?php

use Magento\Framework\App\Action\Action;

?>
<?php if ($exist = ($block->getLatestProduct() && $block->getLatestProduct()->getSize())):?>
<?php
    $blockObj= $block->getLayout()->createBlock('Magento\CatalogWidget\Block\Product\ProductsList');
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'product_page_main_image';
    $title = "RECENTLY ADDED";
    $items = $block->getLatestProduct()->getItems();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    // $templateType =  \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;
    $meigee_helper = $this->helper('\Meigee\Barbour\Helper\BarbourGeneral');
    $lightbox_status = $meigee_helper->getCustomThemeOptionCnf('barbour_lightbox', 'lightbox_status');
    $lightbox_widget_status = $meigee_helper->getCustomThemeOptionCnf('barbour_lightbox', 'lightbox_home');

    $name_align = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'product_name_aligment');
    $stock_status = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'stock_status');
    $quickview_status = $this->helper('WeltPixel\Quickview\Helper\Data')->getConfig('weltpixel_quickview/general/enable_product_listing');
    $quickview_btn = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'quickview_btn');

    $labels_type = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_type');
    $label_new = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_new');
    $label_sale = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_sale');
    $label_sale_percentage = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_sale_percentage');

    $image_hover_status = $meigee_helper->getCustomThemeOptionCnf('barbour_image_hover', 'image_hover_status');
    $image_hover_effect = $meigee_helper->getCustomThemeOptionCnf('barbour_image_hover', 'image_hover_type');
    $rand = rand(5, 1500);
    $visibleProducts = 4;
    switch($visibleProducts){
        case 1:
            $productsPerRow = 'one-column';
        break;
        case 2:
            $productsPerRow = 'two-columns';
        break;
        case 3:
            $productsPerRow = 'three-columns';
        break;
        case 4:
            $productsPerRow = 'four-columns';
        break;
        case 5:
            $productsPerRow = 'five-columns';
        break;
        case 6:
            $productsPerRow = 'six-columns';
        break;
    }
    $front_helper = $this->helper('\Meigee\Barbour\Helper\FrontHelper');
    $type_price = $type;
?>
<div class="block widget block-products-list widget-slider <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title):?>
        <h1 class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </h1>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> products-widget-slider <?php /* @escapeNotVerified */ echo $mode .' '. $type; echo ' '.$productsPerRow; if($image_hover_status){echo $image_hover_effect ? ' hover-scale' : ' hover-simple';} ?>">
                <div class="recently_slider product-items owl-carousel owl-theme clearfix">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php if ($_item->getTypeID() != 'mpgiftcard' && $_item->isAvailable()) { ?>
                            <?php if ($block->getStockItemStatus($_item) == 'In Stock') { ?>
                                <div class="product-item-info clearfix<?php echo !$_item->isAvailable() ? ' sold-out' : ''; ?>">
                                    <div class="indent product-hover-1">
                                        <div class="image-wrapper">
                                            <a href="<?php /* @escapeNotVerified */ echo $blockObj->getProductUrl($_item) ?>" class="product-item-photo">
                                            <?php
                                                $hoverImage = $image_hover_status ? $_item->getHoverImage() : false;
                                                $productImage = $blockObj->getImage($_item, $image, array('data-hover-image'=>null, "loading"=>"lazy"));
                                                echo $productImage->toHtml();
                                                ?>
                                            </a>
                                            <?php
                                                if($front_helper->isProductNew($_item) || $front_helper->isProductSale($_item) || $front_helper->isProductOnlyLeft($_item)){
                                                    echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_item) && $front_helper->isProductSale($_item)) || ($front_helper->isProductNew($_item) && $front_helper->isProductOnlyLeft($_item)) ? ' two-items' : '').'">';
                                                        if ($front_helper->isProductOnlyLeft($_item) && $label_sale) {
                                                            echo $front_helper->isProductOnlyLeft($_item);
                                                        }
                                                        elseif($front_helper->getProductSalePercent($_item) && $label_sale) {
                                                            echo $front_helper->getProductSalePercent($_item);
                                                        } elseif ($front_helper->isProductSale($_item) && $label_sale) {
                                                            echo '<span class="label-sale">'.__('sale').'</span>';
                                                        }
                                                    echo '</div>';
                                                }
                                            ?>
                                            <div class="hover-buttons">
                                                <?php if($lightbox_status && $lightbox_widget_status){ ?>
                                                    <?php if ($_item->getData('thumbnail')) { ?>
                                                        <a href="<?php echo $this->getUrl() . 'pub/media/catalog/product/' .$_item->getData('thumbnail');  ?>" class="lightbox-button" data-toggle="lightbox" data-footer="<?php echo $block->escapeHtml($_item->getName()); ?>" title="<?php echo __('Lightbox'); ?>">
                                                    <?php } else {  ?>
                                                        <a href="<?php echo $productImage->getImageUrl();  ?>" class="lightbox-button" data-toggle="lightbox" data-footer="<?php echo $block->escapeHtml($_item->getName()); ?>" title="<?php echo __('Lightbox'); ?>">
                                                    <?php } ?>
                                                        <i class="meigee-zoom"></i>
                                                    </a>
                                                <?php } ?>
                                                <?php if ($showWishlist || $showCompare): ?>
                                                    <div class="add-to-links" data-role="add-to-links">
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                            <a href="#"
                                                               data-post='<?php /* @escapeNotVerified */ echo $blockObj->getAddToWishlistParams($_item); ?>'
                                                               class="action towishlist" data-action="add-to-wishlist"
                                                               title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($blockObj->getAddToCompareUrl() && $showCompare): ?>
                                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                            <a href="#" class="action tocompare"
                                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                                               title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                                <i class="meigee-chart"></i>
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                                <?php if($quickview_btn && $quickview_status) { ?>
                                                <a href="javascript: void(0);" data-quickview-url="<?php echo $blockObj->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_item->getEntityId()); ?>" class="weltpixel-quickview"><i class="meigee-fa-eye"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
                                                <?php } ?>
                                                <?php if($showCart){ ?>
                                                    <div class="product-action-wrapper">
                                                        <?php if ($showCart): ?>
                                                            <?php if ($_item->isSaleable()): ?>
                                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                                    <button class="btn btn-default btn-cart action tocart"
                                                                         data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $blockObj->getAddToCartUrl($_item) ?>"}}'
                                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                        <i class="meigee-cart"></i>
                                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                <?php else: ?>
                                                                    <?php
                                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                        $postData = $postDataHelper->getPostData($blockObj->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                    ?>
                                                                    <button class="btn btn-default btn-cart"
                                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                        <i class="meigee-cart"></i>
                                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                    </button>
                                                                <?php endif; ?>
                                                            <?php else: ?>
                                                                <a href="<?php /* @escapeNotVerified */ echo $blockObj->getProductUrl($_item) ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php }?>
                                            </div>
                                            <?php if (!$_item->isAvailable()): ?>
                                                <div class="sold-out-label">
                                                    <span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                        <div class="product-item-details">
                                            <h4 class="product-item-name <?php echo $name_align; ?>">
                                                <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                                   href="<?php /* @escapeNotVerified */ echo $blockObj->getProductUrl($_item) ?>"
                                                   class="product-item-link">
                                                    <?php echo $block->escapeHtml($_item->getName()) ?>
                                                </a>
                                            </h4>
                                            <?php if($blockObj->getProductPriceHtml($_item, $type)) { ?>
                                                <?php echo str_replace('grid', 'grid-'.$rand.'-product-'.$_item->getId().'', $blockObj->getProductPriceHtml($_item, $type)); ?>
                                            <?php } ?>
                                            <div class="product_member_price">
                                            <?php if ($_item->getData('member_price')) { ?>
                                                <?php 
                                                $member_price = $_item->getData('member_price');
                                                $member_price = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($member_price,true,false);
                                                $block_obj_custom = $this->getLayout()->createBlock('Winestop\Custom\Block\Customdata');
                                                $is_login = $block_obj_custom->isCustomerLoggedIn();
                                                ?>
                                                <?php if ($is_login) { ?>
                                                    <!-- <div class="product_member_price"> -->                                        
                                                        <div class="price_label">
                                                            <span>Member Price: </span>
                                                            <span><?php echo $member_price; ?></span>
                                                        </div>
                                                    <!-- </div> -->
                                                <?php }else{ ?>
                                                    <!-- <div class="product_member_price"> -->
                                                        <div class="price_label not_login">
                                                            <a href="/customer/account/login/"><span>Member Price</span></a>
                                                        </div>
                                                    <!-- </div> -->
                                                <?php } ?>                                        
                                            <?php } ?>
                                            </div>
                                            <?php 
                                                $productnew = $block->getAttributeobj();
                                            ?>
                                            <?php
                                        //labels start
                                        $specialArr = [];
                                        $newProduct = $productnew->isNewArrival($_item);
                                            if($newProduct){
                                                $specialArr['New Arrival']=$newProduct;
                                            }
                                        ?>
                                        <?php
                                        $specialAssignment = $productnew->getSpecialAttribute($_item);

                                        if ($specialAssignment) {
                                            foreach ($specialAssignment as $key => $assignValue) {
                                                if($newProduct) {
                                                    if ($assignValue) {
                                                        $className = $productnew->getClassName($assignValue); 
                                                        $specialArr[$className]=$assignValue;
                                                        break;
                                                    }
                                                }else{
                                                    if($key>1){
                                                        break;
                                                    }
                                                    if ($assignValue) {
                                                        $className = $productnew->getClassName($assignValue); 
                                                        $specialArr[$className]=$assignValue;
                                                    }
                                                }
                                            }
                                        }
                                        //if(count($specialArr)):?>
                                            <div class="labels">
                                                <?php foreach ($specialArr as $className => $_assignValue) :?>
                                                    <label for="<?=($className=='New Arrival')?'newarrival':'specialattribute'?>">
                                                        <span class="<?=($className=='New Arrival')?'newarrival':$className ?>">
                                                            <img class="white-icon" src="<?php echo $this->getViewFileUrl('images/'.$className.'.png'); ?>" alt="<?php $_assignValue ?>" height="auto">
                                                        </span>
                                                    </label>
                                                <?php endforeach;?>
                                            </div>
                                        <?php //endif;?>
                                        <?php //labels end ?>
                                            <?php
                                                $all_wine_rating = array("ag_rating", "bh_rating", "cg_rating","gr_rating","jd_rating",
                                                          "jh_rating","js_rating","pr_rating","rp_rating","st_rating",
                                                          "wa_rating","we_rating","wns_rating","wn_rating","ws_rating","d_rating","sk_rating","jg_rating");
                                                $cnt = 0;
                                            ?>
                                            <div class="wine_rating_block">
                                                <?php foreach($all_wine_rating as $Wine_rating) { ?>
                                                        <?php if (null !== $_item->getCustomAttribute($Wine_rating) && null !== $_item->getCustomAttribute($Wine_rating."_low")) {
                                                            $rating_label = substr($Wine_rating, 0, strpos($Wine_rating, '_'));
                                                            if ($rating_label == 'wns') {
                                                                $rating_label = 'w&s';
                                                            }
                                                            if ($rating_label == 'ag') {
                                                                $rating_label = 'V';
                                                            }
                                                         ?>
                                                                <?php if ($cnt == 0) { ?>
                                                                    <div class="rating_label">
                                                                        <span>Rating(s)</span>
                                                                    </div>
                                                                    <?php $cnt++; ?>
                                                                <?php } ?>
                                                                <div class="wine_rate_box_combo wine_rate_box">
                                                                    <a href="/rating-guide">
                                                                    <span><?php echo strtoupper($rating_label); ?></span>
                                                                    <span><?php echo $_item->getAttributeText($Wine_rating."_low") . " - "; ?></span>
                                                                    <span><?php echo $_item->getAttributeText($Wine_rating); ?></span>
                                                                    </a>
                                                                </div>
                                                        <?php } else { ?>
                                                            <?php if (null !== $_item->getCustomAttribute($Wine_rating)) { ?>
                                                                <?php $rating_label = substr($Wine_rating, 0, strpos($Wine_rating, '_'));
                                                                    if ($rating_label == 'wns') {
                                                                        $rating_label = 'w&s';
                                                                    }
                                                                    if ($rating_label == 'ag') {
                                                                        $rating_label = 'V';
                                                                    }
                                                                 ?>
                                                                <?php if ($cnt == 0) { ?>
                                                                    <div class="rating_label">
                                                                        <span>Rating(s)</span>
                                                                    </div>
                                                                    <?php $cnt++; ?>
                                                                <?php } ?>
                                                                    <div class="wine_rate_box">
                                                                        <a href="/rating-guide">
                                                                        <span><?php echo $_item->getAttributeText($Wine_rating); ?></span>
                                                                        <span><?php echo strtoupper($rating_label); ?></span>
                                                                        </a>
                                                                    </div>
                                                            <?php } ?>
                                                                <?php if (null !== $_item->getCustomAttribute($Wine_rating."_low")) { ?>
                                                                    <?php $rating_label = substr($Wine_rating."_low", 0, strpos($Wine_rating."_low", '_'));
                                                                        if ($rating_label == 'wns') {
                                                                            $rating_label = 'w&s';
                                                                        }
                                                                        if ($rating_label == 'ag') {
                                                                            $rating_label = 'V';
                                                                        }
                                                                    ?>
                                                                    <?php if ($cnt == 0) { ?>
                                                                        <div class="rating_label">
                                                                            <span>Rating(s)</span>
                                                                        </div>
                                                                        <?php $cnt++; ?>
                                                                    <?php } ?>
                                                                    <div class="wine_rate_box">
                                                                        <a href="/rating-guide">
                                                                        <span><?php echo $_item->getAttributeText($Wine_rating."_low"); ?></span>
                                                                        <span><?php echo strtoupper($rating_label); ?></span>
                                                                        </a>
                                                                    </div>
                                                                <?php } ?>
                                                        <?php } ?>
                                                <?php } ?>
                                            </div>
                                            <div class="availableqty">
                                                <?php
                                                 $productId = $_item->getId();
                                                 $qty = $productnew->getStockItem($productId);
                                                ?>
                                                <?php if ($qty>0): ?>
                                                <label for="availableqty">Inventory : </label>
                                                <?php if ($qty > 24) : ?>
                                                <span><?php echo "24+"; ?></span>
                                                <?php else: ?>
                                                <span><?= $qty ?></span>
                                                <?php endif; ?>
                                                <?php else: ?>
                                                <label for="outofstock" class="outofstock">Inventory : </label>
                                                <span class="outofstock"><?php echo "Out of Stock"; ?></span>
                                                <?php endif;?>
                                            </div>
                                            <?php if ($_item->isSaleable()){ 
                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                $postData = $postDataHelper->getPostData($blockObj->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
                                                // if ($_SERVER['REMOTE_ADDR'] == '103.254.244.46') {
                                                //     echo "<pre>";
                                                //     print_r($postData);
                                                //     exit;
                                                // }
                                                $postParams = json_decode($postData, true);
                                                ?>
                                            <form class="customform" data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="btn btn-default btn-cart action tocart primary">
                                                    <span><?php echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                            <?php /*
                                            <button class="btn btn-default btn-cart action tocart"
                                                    data-post='<?php echo $postData; ?>'
                                                    type="button" title="<?php echo __('Add to Cart') ?>">
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                            */ ?>
                                            <?php } ?>                                    
                                            <?php if($stock_status != 4 && $stock_status != 2) {
                                                if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif;
                                            } ?>
                                            <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_item)->toHtml(); ?>
                                            <?php  echo $block->getProductPriceHtml($_item, $type); ?>
                                        </div>
                                    </div>
                                </div>
                            <?php } ?>
                        <?php } ?>
                        <script type="text/x-magento-init">
                            {
                                "[data-role='tocart-form']": {
                                    "catalogAddToCart": {
                                        "bindSubmit": true
                                    }
                                }
                            }
                        </script>
                    <?php endforeach ?>
                </div>
            </div>
            <?php
            if(count($items) > 4){ ?>
                <script type="text/javascript">
                    require(["jquery", "MeigeeCarousel"], function($, owlCarousel)
                    {
                        jQuery('.recently_slider').owlCarousel({
                            margin: 0,
                            nav:false,
                            responsive:{
                                0:{
                                    items:1
                                },
                                480:{
                                    items:1
                                },
                                767:{
                                    items:3
                                },
                                1007:{
                                    items:4
                                },
                                1331:{
                                    items:4
                                }
                            },
                            smartSpeed: 500,
                            dots: false,
                            loop: true,
                            nav: true
                        });
                    });
                </script>
            <?php } ?>
        </div>
    </div>
<?php endif;?>
