<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="blog_post_wrapper">
    <div class="blog_post_container">
        <div class="blog_post_content">
            <?php foreach ($_postCollection as $_post) { ?>
                <?php
                    $_postUrl = $_post->getPostUrl();
                    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
                    $postcontent = $block->getShorContent($_post);
                    $featuredImage = $_post->getFeaturedImage()
                ?>
                <div class="blog_content">
                    <a href="<?php echo($_postUrl) ?>">
                        <div class="blog_image">
                            <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                        </div>
                        <div class="blog_content_wrapper">                        
                            <div class="blog_title">
                                <span><?php echo $_postName; ?></span>
                            </div>
                            <div class="blog_desc_content">
                                <p><?php echo $postcontent; ?></p>
                            </div>
                        </div>
                    </a>
                </div>
            <?php } ?>
        </div>
    </div>    
</div>
<script type="text/javascript">
    var addthis_config = {
        "ui_language": '<?php echo $this->getAddThisLanguage(); ?>',
        "data_track_clickback":false
    }
</script>
<script type="text/javascript" async src="<?php echo '/' . '/' ?>s7.addthis.com/js/250/addthis_widget.js#pubid=<?php echo $this->getAddThisPubId(); ?>"></script>
<?php } ?>