<?php
	$helperobj = $this->helper('Winestop\Custom\Helper\Data');
	$only_wine_state = $helperobj->getConfig('custom/general/only_wine_state');
	$wsb_state = $helperobj->getConfig('custom/general/wsb_state');
	$only_wine_array = explode(",", $only_wine_state);
	$wsb_array = explode(",", $wsb_state);
	$all_option = $only_wine_state . ",". $wsb_state;
	$all_option_array = explode(",", $all_option);
	$state_code_name = [];
	sort($all_option_array);
	$category = $this->helper('Meigee\Barbour\Helper\FrontHelper')->getCurrentCategory();
	$catname = NULL;
	if ($category) {
		if ($category->getName() == 'Spirits' || $category->getName() == 'Beer') {
			$catname = $category->getName();
		}
		if ($category->getParentCategory()->getName() == 'Spirits' || $category->getParentCategory()->getName() == 'Beer') {
			$catname = $category->getParentCategory()->getName();
		}
	}
?>
<div class="header-banner col-md-2">
	<div class="shipping">
		<div class="select-shipping-container">
			<img src='<?php echo $this->getViewFileUrl('images/delivery-truck_1.png'); ?>' alt=''>
			<div class="custom-select">
				<span class="ship-label-content">Ship To</span>
				<select id="custom-delivery-checker" class="delivery-checker" style="width: 88px; float: left; margin-left: 12px;">
					<?php foreach ($all_option_array as $option) { ?>
						<?php
							$region = $helperobj->getStateDetail($option);
							$state_code_name[] = ['code' => $option, 'name' => $region->getData('name')];
						 ?>
						<?php if ($option == 'CA') { ?>
							<option name="<?php echo $region->getData('name'); ?>" value="<?php echo $option; ?>" selected="selected"><?php echo $option; ?></option>
						<?php } else { ?>
							<option name="<?php echo $region->getData('name'); ?>" value="<?php echo $option; ?>"><?php echo $option; ?></option>
						<?php } ?>
					<?php } ?>
				</select>
			</div>
			<span id="custom-delivery-message" style="font-size: 11px; float: left; margin-top: 4px;"></span>
		</div>
	</div>
</div>
<div id="popup-modal">
	<div class="modalWindow">
		<div class="modal_content">
			<div class="cartTransfer_headline">
				<span class="headline"></span>
			</div>
			<div class="poup_cancel"><a class="poup_cancel_state" href="javascript:void(0)"></a></div>
			<div class="cart_item_header">
			</div>
			<div class="items_container">

			</div>
		</div>
	</div>
</div>
<div id="popup-modal-checkout">
	<div class="modalWindow">
		<div class="modal_content">
			<div class="cartTransfer_headline">
				<span class="headline"></span>
			</div>
			<div class="poup_cancel"><a class="poup_cancel_state" href="javascript:void(0)"></a></div>
			<div class="cart_item_header">
			</div>
			<div class="items_container">

			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	require(['jquery', 'jquery/ui'], function($){
     document.getElementById('custom-delivery-checker').addEventListener('change', function () {
     	var wsb_array = <?php echo json_encode($wsb_array); ?>;
     	var current_state = this.value;
		$('.sprite_custom').parent().css('display','none');
     	$.each(wsb_array, function (key, value) {
		   if (current_state == value) {
			$('.sprite_custom').parent().css('display','block');
		   }
		});
	});
 });
</script>
<script type="text/javascript">
 require(['jquery', 'Magento_Ui/js/modal/modal'], function ($,modal)  {
 	$(document).ready(function($) {
		
		// Add Class to Spirits Category
 		$(".level-top").find( ":contains('Spirits')").addClass("sprite_custom");
 		var only_wine_array = <?php echo json_encode($only_wine_array); ?>;
 		var wsb_array = <?php echo json_encode($wsb_array); ?>;
 		var state_code_name = <?php echo json_encode($state_code_name); ?>;
 		var shipto = sessionStorage.getItem("shipto");
 		var catname = "<?php echo $catname ?>";
 		var temp;
 		var temp_old_shipto_state;
 		if (shipto) {
 			$('.delivery-checker').val(shipto);
 			$.each(wsb_array, function (key, value) {
			    if (shipto == value) {
				 $("#custom-delivery-message").text("DELIVER WINE,SPIRITS & BEER");
			   }
			});
			$.each(only_wine_array, function (key, value) {
			    if (shipto == value) {
					$("#custom-delivery-message").text("DELIVER WINE ONLY");
			   }
			});
 		}
 		else
 		{
 			$('.delivery-checker').val('CA');
 			$("#custom-delivery-message").text("DELIVER WINE,SPIRITS & BEER");
 			sessionStorage.setItem("shipto", 'CA');
 			sessionStorage.setItem("old_shipto", "CA");
 			sessionStorage.setItem("shipto_state","12");
 		}
 		var shipto_state = sessionStorage.getItem("shipto_state");
 		if (shipto_state) {
			if(!$('body').hasClass('onestepcheckout-index-index')){
 			var checkinterval = setInterval(function () {
 				$(".onestep-shipping-address .select[name=region_id] > option").each(function () {
 					if ($(this).val() == shipto_state) {
 						$(this).attr('selected','selected');
 						if (checkinterval) {
 							clearInterval(checkinterval);
 						}
 					}

 				});
 			}, 1000);
			}
		}
		if (catname == 'Spirits' || catname == 'Beer') {
			$('.custom_ship_to').css('display','none');
		    $('.sidebar.col-sm-3.left-sidebar').css('display','none');
		    $('.ship_to_message').css('display','block');
		}
		$('.sprite_custom').parent().css('display','none');
		var shipto = sessionStorage.getItem("shipto");
     	$.each(wsb_array, function (key, value) {
		    if (shipto == value) {
			$('.sprite_custom').parent().css('display','block');
		   }
		});
 		$.each(wsb_array, function (key, value) {
	 		if (catname == 'Spirits' || catname == 'Beer') {
				if (shipto == value) {
			    	$('.ship_to_message').css('display','none');
			        $('.sidebar.col-sm-3.left-sidebar').css('display','block');
			        $('.custom_ship_to').css('display','block');
	 			}
			}
		});
		$('#popup-modal-checkout').on('modalclosed', function() {
			$(".onestep-shipping-address form [name=region_id]").prop("selectedIndex", 0).change();
		 	var old_shipto = sessionStorage.getItem("old_shipto");
			  if (temp != 'undefined' && temp) {
	 			$('.delivery-checker').val(temp);
	 			sessionStorage.setItem("old_shipto", temp);
	 			sessionStorage.setItem("shipto", temp);
		 		  $.each(wsb_array, function (key, value) {
				    if (temp == value) {
					 $("#custom-delivery-message").text("DELIVER WINE,SPIRITS & BEER");
				   }
				});
				$.each(only_wine_array, function (key, value) {
				    if (temp == value) {
					$("#custom-delivery-message").text("DELIVER WINE ONLY");
				   }
				});
			}

	 			var old_shipto_state = sessionStorage.getItem("old_shipto_state");
				  $('.sprite_custom').parent().css('display','block');
	 		  	if (temp_old_shipto_state) {
				if(!$('body').hasClass('onestepcheckout-index-index')){
					var checkinterval = setInterval(function () {
						$(".onestep-shipping-address .select[name=region_id] > option").each(function () {
							if ($(this).text() == temp_old_shipto_state) {
								$(this).attr('selected','selected');
								sessionStorage.setItem("old_shipto_state", temp_old_shipto_state);
								if (checkinterval) {
									clearInterval(checkinterval);
								}
							}

						});
					}, 1000);
				}
			}
		});
		$("body .modal_content .poup_cancel_state").click(function() {
			$('#popup-modal-checkout').modal('closeModal');
			$(".onestep-shipping-address form [name=region_id]").prop("selectedIndex", 0).change();
		});
		$(document).on('focus',".onestep-shipping-address form [name=region_id]",function(){
			var code;
			var state = $(this).find(":selected").text();
			$.each(state_code_name, function (key, value) {
	 			if (value.name == state) {
	 				code = value.code;
	 			}
	 		});
	        sessionStorage.setItem("old_shipto", code);
	        sessionStorage.setItem("old_shipto_state", state);

	    });
		$(document).on('change',".onestep-shipping-address form [name=region_id]",function(){
       		var customurl = "<?php echo $this->getUrl().'custom/index/Deliverycheckercontroller'?>";
       		var code = this.value;
				$.ajax({
	                url: customurl,
	                type: "post",
	                data: {'code': code, 'catname': catname},
	                success: function(checker) {
		                var checker = jQuery.parseJSON(checker);
		                if (checker) {
		                	if (!checker.abel_to_change) {
								// window.allowRegionId = false;
                            	// $(".actions-toolbar span.placeorder-disallow").text("Please change your shipping address");
		                		if (checker.region_name) {
			                		var items = checker.item;
			                    	var html;
			                    	var headline = checker.item_count + ' Item in your cart cannot be shipped to ' + checker.region_name;
			                    	$("span.headline" ).text(headline);
			                    	var old_shipto = sessionStorage.getItem("shipto");
			                    	var old_shipto_state = sessionStorage.getItem("old_shipto_state");
			                    	temp_old_shipto_state = old_shipto_state
			                    	var cancel_link = "Cancel";
		                    		$("a.poup_cancel_state" ).text(cancel_link);
			                    	var header_line = '<span>The following item will be removed</span>';
			                    	$("div.cart_item_header" ).replaceWith(header_line);
			                    	var product_ids;
			                    	for (i = 0; i < items.length; i++) {
			                    		var item = items[i];
			                    		if (html) {
			                    			html = html + '<div class="cart_item"><div class="item_image_content"><img src="' + item.image_url +'"></div><div class="ship_item_content"><span class="item-name">' + item.name +'</span><span class="item_price">' + item.price +'</span></div></div>';
			                    			product_ids = product_ids + "," + item.item_id;
			                    		}
			                    		else
			                    		{
			                    			html = '<div class="cart_item"><div class="item_image_content"><img src="' + item.image_url +'"></div><div class="ship_item_content"><span class="item-name">' + item.name +'</span><span class="item_price">' + item.price +'</span></div></div>';
			                    			product_ids = item.item_id;
			                    		}
									}
									$("div.items_container" ).replaceWith(html);
			                    	var options = {
						                type: 'popup',
						                responsive: true,
						                innerScroll: true,
						                modalClass: 'ship_to_popup_model',
						                buttons: [{
						                    text: $.mage.__('Continue (ship to ' + checker.region_code + ' )'),
						                    class: '',
						                    click: function () {
						                    	var product_ids = sessionStorage.getItem("product_ids");
						                    	var customurl = "<?php echo $this->getUrl().'custom/index/Remove'?>";
												$.ajax({
									                url: customurl,
									                type: "post",
									                data: {'product_ids': product_ids},
									                success: function(checker) {
										                var checker = jQuery.parseJSON(checker);
										                if (checker) {
										        		    $('.sprite_custom').parent().css('display','none');
											                if (checker.success) {
											                	 window.location.href='/';
											                	 var checkout_ship_to_code = sessionStorage.getItem("checkout_ship_to_code");
											                	$('.delivery-checker').val(checkout_ship_to_code);
											                	sessionStorage.setItem("shipto", checkout_ship_to_code);
											                }
											            }
									                }
									            });
						                        this.closeModal();
						                    }
						                }]
						            };
						        	var popup = modal(options, $('#popup-modal-checkout'));
									$('#popup-modal-checkout').modal('openModal');
									//sessionStorage.setItem("old_shipto", shipto);
									sessionStorage.setItem("product_ids", product_ids);
									sessionStorage.setItem("checkout_ship_to_code", checker.region_code);
								}
								localStorage.setItem("first_time","1");
		                	}
		                	else
		                	{
		                		sessionStorage.setItem("shipto_state",checker.regionId);
								window.allowRegionId = true;
                            	$(".actions-toolbar span.placeorder-disallow").text("");
		                	}
		                }
	                }
	            });
    	});
    	$("#custom-delivery-checker").on('focus', function () {
	        var state = $(this).find('option:selected').attr("name");
	        sessionStorage.setItem("old_shipto", this.value);
	        sessionStorage.setItem("old_shipto_state", state);
	    }).change(function() {
	           var code = this.value;
	           var catname = "<?php echo $catname ?>";
	           var customurl = "<?php echo $this->getUrl().'custom/index/Deliverycheckercontroller'?>";
				$.ajax({
	                url: customurl,
	                type: "post",
	                data: {'code': code, 'catname': catname},
	                success: function(checker) {
		                var checker = jQuery.parseJSON(checker);
	                	if (checker) {
	                		$("#custom-delivery-message" ).text(checker.message);
		                    if (!checker.abel_to_change) {
		                    	var items = checker.item;
		                    	var html;
		                    	var headline = checker.item_count + ' Item in your cart cannot be shipped to ' + checker.region_name;
		                    	$("span.headline" ).text(headline);
		                    	var old_shipto = sessionStorage.getItem("old_shipto");
		                    	temp = old_shipto;
		                    	var old_shipto_state = sessionStorage.getItem("old_shipto_state");
		                    	temp_old_shipto_state = old_shipto_state
		                    	var cancel_link = "Cancel (Stay in " + old_shipto + " )";
		                    	$("a.poup_cancel_state" ).text(cancel_link);
		                    	var header_line = '<span>The following item will be removed</span>';
		                    	$("div.cart_item_header" ).replaceWith(header_line);
		                    	var product_ids;
		                    	for (i = 0; i < items.length; i++) {
		                    		var item = items[i];
		                    		if (html) {
		                    			html = html + '<div class="cart_item"><div class="item_image_content"><img src="' + item.image_url +'"></div><div class="ship_item_content"><span class="item-name">' + item.name +'</span><span class="item_price">' + item.price +'</span></div></div>';
		                    			product_ids = product_ids + "," + item.item_id;
		                    		}
		                    		else
		                    		{
		                    			html = '<div class="cart_item"><div class="item_image_content"><img src="' + item.image_url +'"></div><div class="ship_item_content"><span class="item-name">' + item.name +'</span><span class="item_price">' + item.price +'</span></div></div>';
		                    			product_ids = item.item_id;
		                    		}
		                    		//alert(JSON.stringify(items[i]));
		                    		//alert(html);
		                    		//alert(items[i].item_id);
								}
		                    	$("div.items_container" ).replaceWith(html);
		                    	var options = {
					                type: 'popup',
					                responsive: true,
					                innerScroll: true,
					                modalClass: 'ship_to_popup_model',
					                buttons: [{
					                    text: $.mage.__('Continue (ship to ' + code + ' )'),
					                    class: '',
					                    click: function () {
					                    	var product_ids = sessionStorage.getItem("product_ids");
					                    	var customurl = "<?php echo $this->getUrl().'custom/index/Remove'?>";
											$.ajax({
								                url: customurl,
								                type: "post",
								                data: {'product_ids': product_ids},
								                success: function(checker) {
									                var checker = jQuery.parseJSON(checker);
													$('.sprite_custom').parent().css('display','none');
									                if (checker) {
										                if (checker.success) {
										                	 window.location.href='/';
										                	 sessionStorage.setItem("shipto", code);
										                }
										            }
								                }
								            });
					                        this.closeModal();
					                    }
					                }]
					            };
					        	var popup = modal(options, $('#popup-modal-checkout'));
								$('#popup-modal-checkout').modal('openModal');
								sessionStorage.setItem("product_ids", product_ids);
		                    	checker.status = false;
		                    	
		                    }
		                    sessionStorage.setItem("shipto", code);
		                    sessionStorage.setItem("shipto_state", checker.regionId);
		                    if (checker.status) {
		                        $('.custom_ship_to').css('display','none');
		                        $('.sidebar.col-sm-3.left-sidebar').css('display','none');
		                        $('.ship_to_message').css('display','block');
		                    }
		                    else
		                    {
		                    	$('.ship_to_message').css('display','none');
		                    	$('.sidebar.col-sm-3.left-sidebar').css('display','block');
		                    	$('.custom_ship_to').css('display','block');
		                    }
	                    }
	                }
	            });
	    });
	});
});
</script>
<script type="text/javascript">
require(['jquery', 'jquery/ui'], function($){
	$(document).ready(function($) {
		$('#email_address_0').attr("placeholder", "Your Email Address");
	});
});
</script>

