<div class="shop_by_container">
  <?php
echo $this->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('shop_by_type')
->toHtml();
?>
</div>
<script type="text/javascript">
require(["jquery", "MeigeeCarousel"], function($, owlCarousel)
{                            
    jQuery('.shop_type_by').owlCarousel({
        margin: 0,
        nav:true,
        responsive:{
            0:{
                items:1
            },
            375:{
                items:2
            },
            767:{
                items:3
            },
            1007:{
                items:4
            },
            1331:{
                items:5
            }
        },
        smartSpeed: 500,
        dots: false,
        loop: true,
        navigation: true,
        navText: ['<i class="meigee-left-arrow-key"></i>','<i class="meigee-right-arrow-key"></i>']
    });
});
</script>