<?php $_product = $block->getProduct(); ?>
<?php if (!$_product->isAvailable()){ ?>
<div class="notify_me_container product-add-form">
	<div class="notify_me_content">
		<form action="#" class="notify-form" method="post" id="notify-form" data-role="notify-me-form" novalidate="novalidate">
			<input class="form-control" type="email" id="email" name="email" placeholder="Enter Your Email">
			<button type="submit" value="Submit" class="action submit btn btn-default">Notify Me</button>
		</form>		
	</div>
</div>
<?php } ?>