<?php 
$_product = $block->getProduct();
$viewModel = $block->getData('view_model');
?>
<?php
//labels start
$specialArr = [];
$newProduct = $viewModel->isNewArrival($_product);
    if($newProduct){
        $specialArr['New Arrival']=$newProduct;
    }
?>
<?php
$specialAssignment = $viewModel->getSpecialAttribute($_product);

if ($specialAssignment) {
    foreach ($specialAssignment as $key => $assignValue) {
        if($newProduct) {
            if ($assignValue) {
                $className = $viewModel->getClassName($assignValue); 
                $specialArr[$className]=$assignValue;
                break;
            }
        }else{
            if($key>1){
                break;
            }
            if ($assignValue) {
                $className = $viewModel->getClassName($assignValue); 
                $specialArr[$className]=$assignValue;
            }
        }
    }
}
if(count($specialArr)):?>
    <div class="labels">
        <?php foreach ($specialArr as $className => $_assignValue) :?>
            <label for="<?=($className=='New Arrival')?'newarrival':'specialattribute'?>">
                <span class="<?=($className=='New Arrival')?'newarrival':$className ?>">
                    <img class="white-icon" src="<?php echo $this->getViewFileUrl('images/'.$className.'.png'); ?>" alt="<?php $_assignValue ?>" height="auto">
                </span>
            </label>
        <?php endforeach;?>
    </div>
<?php endif;?>
<?php //labels end ?>