<?php $_item = $block->getProduct(); ?>
<?php
$all_wine_rating = array("ag_rating","ba_rating","bh_rating","cg_rating","d_rating","gr_rating","jd_rating","jg_rating","jh_rating","js_rating","pr_rating","rb_rating","rp_rating","sk_rating","st_rating","tb_rating","wa_rating","we_rating","wns_rating","wn_rating","ws_rating");
?>
<?php foreach($all_wine_rating as $Wine_rating) { ?> 	                 

	<?php if (null == $_item->getCustomAttribute($Wine_rating) || null !== $_item->getCustomAttribute($Wine_rating)) { ?>
		<?php
			$rating_label =  $_item->getResource()->getAttribute($Wine_rating)->getFrontend()->getLabel($_item);
			$rating_label = substr($rating_label, 0, strpos($rating_label, ' ('));
			$rating_content = $_item->getResource()->getAttribute($Wine_rating)->getFrontend()->getValue($_item);
			$attr_code = substr($Wine_rating, 0, strpos($Wine_rating, '_')) . "_review";
			if($Wine_rating == 'd_rating')
			{
				$attr_code = 'dm_review';
			}
			$review_label =  $_item->getResource()->getAttribute($attr_code)->getFrontend()->getLabel($_item);
			$review_content = $_item->getResource()->getAttribute($attr_code)->getFrontend()->getValue($_item);
	    ?>
    	<?php if ($rating_content) { ?>	
			<div class="wine_rating_container">
				<?php 
					if (null !== $_item->getCustomAttribute($Wine_rating."_low")):
						$_low_rating_content = $_item->getResource()->getAttribute($Wine_rating."_low")->getFrontend()->getValue($_item);
				?>
					<span><?php echo strtoupper($rating_label) . ": ".$_low_rating_content." - ". $rating_content; ?></span>
				<?php else:?>
					<span><?php echo strtoupper($rating_label) . ": " . $rating_content; ?></span>
				<?php endif;?>
			</div>
		<?php } ?>
		<?php if ($review_content) { ?>				
			<div class="wine_review_content">
				<span><?php echo strtoupper($review_label) . ": " . $review_content; ?></span>					
			</div>
		<?php } ?>
	<?php } ?> 	
	<?php /*if (null !== $_item->getCustomAttribute($Wine_rating."_low")) { ?>		
		<?php
			$Wine_rating = $Wine_rating."_low";
			$rating_label =  $_item->getResource()->getAttribute($Wine_rating)->getFrontend()->getLabel($_item);
			$rating_label = substr($rating_label, 0, strpos($rating_label, ' ('));
			$rating_content = $_item->getResource()->getAttribute($Wine_rating)->getFrontend()->getValue($_item);
			$attr_code = substr($Wine_rating, 0, strpos($Wine_rating, '_')) . "_review";
			$review_label =  $_item->getResource()->getAttribute($attr_code)->getFrontend()->getLabel($_item);
			$review_content = $_item->getResource()->getAttribute($attr_code)->getFrontend()->getValue($_item);		
	    ?>		
		<div class="wine_rating_container">
			<span><?php echo strtoupper($rating_label) . ": " . $rating_content; ?></span>			
		</div>			
		<div class="wine_review_content">
			<span><?php echo strtoupper($review_label) . ": " . $review_content; ?></span>					
		</div>
	<?php } */?>
<?php } ?>
