<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<?php
$cnt=0;
?>
<?php
        $filter_class_name = str_replace(" ", "_", $filterItems[0]->getName()); 
        $filter_class_name = preg_replace('/[^A-Za-z0-9\-]/', '', $filter_class_name);
    ?>
<ol class="items">
    <?php foreach ($filterItems as $filterItem) : ?>
        <?php
            if ($cnt < 5) {
                 $class_label = 'item';
                 $cnt++;
             }
             else
             {
                $class_label = 'item sho_hide_content_' . $filter_class_name;
                $cnt++;
             } 
        ?>
        <li class="<?php echo($class_label); ?>">
            <?php if ($filterItem->getCount() > 0) : ?>
                <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>">
                    <span class="filter-label"><?php /* @noEscape */ echo ($filterItem->getLabel() == 'Spirits' ? 'Malt' : $filterItem->getLabel()); ?></span>
                    <!-- <span class="filter-label"><?php /* @noEscape */ //echo $filterItem->getLabel() ?></span> -->
                    <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                        <span class="count"><?php /* @noEscape */ echo "(".(int)$filterItem->getCount().")"?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1) : ?> <?php echo $block->escapeHtml(__('item')) ?><?php else :?> <?php echo $block->escapeHtml(__('items')) ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php else:?>
                <?php /* @noEscape */ echo $filterItem->getLabel() ?>
                <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                    <span class="count"><?php /* @noEscape */ echo "(".(int)$filterItem->getCount().")"?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1) : ?><?php echo $block->escapeHtml(__('item')) ?><?php else : ?><?php echo $block->escapeHtml(__('items')) ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>    
    <?php if (count($filterItems) > 5) : ?>
    <a href="javascript:void(0)" class="show_all_<?php echo($filter_class_name); ?> show_more" id="<?php echo($filter_class_name); ?>">View More</a>
    <a href="javascript:void(0)" class="show_less_<?php echo($filter_class_name); ?> show_less" id="<?php echo($filter_class_name); ?>">View Less</a>
    <?php endif; ?>
</ol>
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        $(document).ready(function () {
            $(".sho_hide_content_" + '<?php echo($filter_class_name); ?>').hide();
            $(".show_less_" + '<?php echo($filter_class_name); ?>').hide();         
            $(".show_more").click(function(){
                var filter_id = $(this).attr('id');               
                if ( $( this ).hasClass( "show_all_<?php echo($filter_class_name); ?>" ) ) {                    
                    $('.sho_hide_content_' + '<?php echo($filter_class_name); ?>').show();
                    $('.show_all_<?php echo($filter_class_name); ?>').hide();
                    $('.show_less_<?php echo($filter_class_name); ?>').show();             
                }                
            });
            $(".show_less").click(function(){
                var filter_id = $(this).attr('id');
                if ( $( this ).hasClass( "show_less_<?php echo($filter_class_name); ?>" ) ) {
                    $('.sho_hide_content_' + '<?php echo($filter_class_name); ?>').hide();
                    $('.show_all_<?php echo($filter_class_name); ?>').show();
                    $('.show_less_<?php echo($filter_class_name); ?>').hide();
                }
            });            
        });
    });
</script>