<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
 // phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
$viewModel = $block->getData('view_model');
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$productLabelHelper = $this->helper(Winestop\Custom\Helper\Data::class);
?>
<div class="ship_to_message" style="display: none;">
	<div class="message info empty"><div><?php echo $block->escapeHtml(__('Sorry, we do not deliver spirits to your state')) ?></div></div>
</div>
<div class="custom_ship_to">
	<?php if (!$_productCollection->count()): ?>
	    <div class="message info empty"><div><?php echo $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
	<?php else: ?>
	    <?php echo $block->getToolbarHtml() ?>
	    <?php echo $block->getAdditionalHtml() ?>
	    <?php
		$meigee_helper = $this->helper(\Meigee\Barbour\Helper\BarbourGeneral::class);
	    if ($block->getMode() == 'grid') {
	        $viewMode = 'grid';
	        $imageDisplayArea = 'category_page_grid';
	        $showDescription = false;
	        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	        // $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
			$grid_columns = $lightbox_status = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'grid_columns');
	    } else {
	        $viewMode = 'list';
	        $imageDisplayArea = 'category_page_list';
	        $showDescription = true;
	        // $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
	        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
			$grid_columns = '';
	    }
	    /**
	     * Position for actions regarding image size changing in vde if needed
	     */
	    $pos = $block->getPositioned();
		$lightbox_status = $meigee_helper->getCustomThemeOptionCnf('barbour_lightbox', 'lightbox_status');
		$lightbox_listing_status = $meigee_helper->getCustomThemeOptionCnf('barbour_lightbox', 'lightbox_listing');
		$product_name = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'product_name');
		$product_price = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'product_price');
		$cart_btn = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'cart_btn');
		$compare_btn = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'compare_btn');
		$wishlist_btn = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'wishlist_btn');
		$name_align = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'product_name_aligment');
		$stock_status = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'stock_status');
	    $image_hover_status = $meigee_helper->getCustomThemeOptionCnf('barbour_image_hover', 'image_hover_status');
	    $image_hover_effect = $meigee_helper->getCustomThemeOptionCnf('barbour_image_hover', 'image_hover_type');
		$quickview_status = $this->helper('WeltPixel\Quickview\Helper\Data')->getConfig('weltpixel_quickview/general/enable_product_listing');
		$quickview_btn = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'quickview_btn');
	    $front_helper = $this->helper(\Meigee\Barbour\Helper\FrontHelper::class);

	    $labels_type = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_type');
	    $label_new = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_new');
	    $label_sale = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_sale');
	    $label_sale_percentage = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_sale_percentage');

		$listingCustomGrid = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'listing_custom_grid');
	    $listingColumnsGridString = preg_replace('/\s+/','',$meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'listing_grid_switcher'));
	    $listingColumnsGrids = explode(',', $listingColumnsGridString);
	    $_columns = array(
	        '1' => 'one-column',
	        '2' => 'two-columns',
	        '3' => 'three-columns',
	        '4' => 'four-columns',
	        '5' => 'five-columns',
	        '6' => 'six-columns',
	        '7' => 'seven-columns',
	        '8' => 'eight-columns'
	    );
	    $_columnsSet = array();
	    foreach ($listingColumnsGrids as $_key => $_listingColumnsGrid) {
	      array_push($_columnsSet, $_columns[$_listingColumnsGrid]);
	    }
	    array_push($_columnsSet, 'one-column');
	    array_push($_columnsSet, 'two-columns');
	    $listingCustomGridCookie = $front_helper->getFrontCookie('barbourListingGridSwitcher');

	    if ($listingCustomGrid == 1) {
	        if ($listingCustomGridCookie) {
	            if(in_array($listingCustomGridCookie,$_columnsSet) == false){
	                $grid_columns = $_columns[array_shift($listingColumnsGrids)];
	            } else {
	                $grid_columns = $listingCustomGridCookie;
	            }
	        } else {
	            $grid_columns = $_columns[array_shift($listingColumnsGrids)];
	        }
	    }
	    ?>
	    <div class="custom_search_result_container">
	    	<div class="search_result">
	    		<span>Your search returned <?php echo $_productCollection->getSize(); ?> results</span>
	    	</div>
	    </div>
	<div class="out_of_stock_container">
	   <input type="checkbox" id="include_ot_of_stock" class="include_ot_of_stock" value="include_out_of_stock">
	   <label for="vehicle1">Include out of stock items</label>
	</div>
	    <div class="products wrapper <?php /* @noEscape */ echo $viewMode; ?> products-<?php /* @noEscape */ echo $viewMode .' '. $grid_columns; if($image_hover_status){echo $image_hover_effect ? ' hover-scale' : ' hover-simple';} ?>">
	        <ol class="products clearfix list items product-items row">
	            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>

				<?php if($viewMode == 'list') { ?>
					 <?php foreach ($_productCollection as $_product): ?>
						<li class="item product product-item">
							<div class="product-item-info clearfix<?php echo !$_product->isAvailable() ? ' sold-out' : ''; ?>" data-container="product-<?= /* @noEscape */ $viewMode ?>">
								<div class="indent product-hover-1">
									<div class="image-wrapper">
										<?php
										$hoverImage = $image_hover_status ? $_product->getHoverImage() : false;
										$productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>null));

										if ($pos != null) {
											$position = ' style="left:' . $productImage->getWidth() . 'px;'
												. 'top:' . $productImage->getHeight() . 'px;"';
										} ?>
										<?php
										$is_bestseller = false;
										if ($_product->getData('special_designations')) {
			                                $spe = explode(",", $_product->getData('special_designations'));
			                                if (in_array('44',$spe)) {
			                                    $is_bestseller = true;
			                                }
			                            }
											if($front_helper->isProductNew($_product) || $front_helper->isProductSale($_product) || $front_helper->isProductOnlyLeft($_product) || $is_bestseller){
												echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_product) && $front_helper->isProductSale($_product)) || ($front_helper->isProductNew($_product) && $front_helper->isProductOnlyLeft($_product)) ? ' two-items' : '').'">';
													
													// if($is_bestseller) {
													// 	echo '<span class="label-best-seller">'.__('Best Seller').'</span>';
													// }
													if ($front_helper->isProductOnlyLeft($_product) && $label_sale) {
														echo $front_helper->isProductOnlyLeft($_product);
													}
													elseif($front_helper->getProductSalePercent($_product) && $label_sale) {
														echo $front_helper->getProductSalePercent($_product);
													} elseif ($front_helper->isProductSale($_product) && $label_sale) {
														echo '<span class="label-sale">'.__('sale').'</span>';
													}
												echo '</div>';
											}
										?>
										<div class="hover-buttons">
											<?php if($lightbox_status && $lightbox_listing_status){ ?>
												<?php if ($_product->getData('thumbnail')) { ?>
                                                        <a href="<?php echo $this->getUrl() . 'pub/media/catalog/product/' .$_product->getData('thumbnail');  ?>" class="lightbox-button"  data-toggle="lightbox" data-footer="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" title="<?php echo __('Lightbox'); ?>">
                                                    <?php } else {  ?>
                                                        <a href="<?php echo $productImage->getImageUrl();  ?>" class="lightbox-button"  data-toggle="lightbox" data-footer="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" title="<?php echo __('Lightbox'); ?>">
                                                    <?php } ?>												
													<i class="meigee-zoom"></i>
												</a>
											<?php } ?>
											<?php if($compare_btn || $wishlist_btn){ ?>
												<div data-role="add-to-links" class="add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
													<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
														<?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
													<?php endif; ?>
												</div>
											<?php } ?>
											<?php if($quickview_btn && $quickview_status) { ?>
												<a href="javascript: void(0);" data-quickview-url="<?php echo $block->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_product->getEntityId()); ?>" class="weltpixel-quickview"><i class="meigee-fa-eye"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
											<?php } ?>
											<?php if($cart_btn){ ?>
												<div class="product-action-wrapper">
													<?php if ($_product->isSaleable()): ?>
														<?php $postParams = $block->getAddToCartPostParams($_product); ?>
														<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php echo $block->escapeUrl($postParams['action']); ?>" method="post">
															<input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
															<input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
															<?php echo $block->getBlockHtml('formkey')?>
															<button type="submit"
																	title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
																	class="action tocart btn btn-default btn-cart">
																<i class="meigee-cart"></i>
																<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
															</button>
														</form>
													<?php else: ?>
														<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
													<?php endif; ?>
												</div>
											<?php } ?>
										</div>
										<?php

										// Product Image ?>

										<a href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
											<?php echo $productImage->toHtml(); ?>
										</a>
											<?php if (!$_product->isAvailable()): ?>
												<div class="sold-out-label">
													<span><?php /* @escapeNotVerified */ echo __('Out Of Stock') ?></span>
												</div>
											<?php endif; ?>

									</div>
									<div class="product details product-item-details">
										<div class="product_content_info">
											<?php if($product_name){
												$_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
												<h4 class="product name product-item-name <?php echo $name_align; ?>">
													<a class="product-item-link"
													   href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>">
														<?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
													</a>
												</h4>
											<?php } ?>
											<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
											<div class="product-item-inner">
												<?php if ($showDescription && $_product->getShortDescription()):?>
													<div class="product description product-item-description"
														data-url="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>"
														data-title="<?php /* @noEscape */ echo $_productNameStripped ?>">
														<?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
														<!-- <a href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>" title="<?php echo $_productNameStripped ?>"
														   class="action more"><?php echo $block->escapeHtml(__('Learn More')) ?></a> -->
													</div>
												<?php endif; ?>
												<?php
                                        		//labels start
		                                        $specialArr = [];
		                                        $newProduct = $productLabelHelper->isNewArrival($_product);
		                                            if($newProduct){
		                                                $specialArr['New Arrival']=$newProduct;
		                                            }
		                                        ?>
		                                        <?php
		                                        $specialAssignment = $productLabelHelper->getSpecialAttribute($_product);
		                                        if ($specialAssignment) {
		                                            foreach ($specialAssignment as $key => $assignValue) {
		                                                if($newProduct) {
		                                                    if ($assignValue) {
		                                                        $className = $productLabelHelper->getClassName($assignValue); 
		                                                        $specialArr[$className]=$assignValue;
		                                                        break;
		                                                    }
		                                                }else{
		                                                    if($key>1){
		                                                        break;
		                                                    }
		                                                    if ($assignValue) {
		                                                        $className = $productLabelHelper->getClassName($assignValue); 
		                                                        $specialArr[$className]=$assignValue;
		                                                    }
		                                                }
		                                            }
		                                        }
		                                        //if(count($specialArr)):
		                                        ?>
		                                            <div class="labels">
		                                                <?php foreach ($specialArr as $className => $_assignValue) :?>
		                                                    <label for="<?=($className=='New Arrival')?'newarrival':'specialattribute'?>">
		                                                        <span class="<?=($className=='New Arrival')?'newarrival':$className ?>">
		                                                            <img class="white-icon" src="<?php echo $this->getViewFileUrl('images/'.$className.'.png'); ?>" alt="<?php $_assignValue ?>" height="auto">
		                                                        </span>
		                                                    </label>
		                                                <?php endforeach;?>
		                                            </div>
		                                        <?php //endif;?>
		                                        <?php //labels end ?>
												
												<div class="swatches-wrapper">
													<?php echo $block->getProductDetailsHtml($_product); ?>
												</div>
												<?php
			                                        $all_wine_rating = array("ag_rating", "bh_rating", "cg_rating","gr_rating","jd_rating",
	                                                      "jh_rating","js_rating","pr_rating","rp_rating","st_rating",
	                                                      "wa_rating","we_rating","wns_rating","wn_rating","ws_rating","d_rating","sk_rating","jg_rating");
			                                        $cnt = 0;
			                                    ?>
			                                    <div class="wine_rating_block">
			                                       <?php foreach($all_wine_rating as $Wine_rating) { ?>
			                                            <?php if (null !== $_product->getCustomAttribute($Wine_rating) && null !== $_product->getCustomAttribute($Wine_rating."_low")) {
			                                            	$rating_label = substr($Wine_rating, 0, strpos($Wine_rating, '_'));
			                                            	if ($rating_label == 'wns') {
			                                            		$rating_label = 'w&s';
			                                            	}
			                                            	if ($rating_label == 'ag') {
                                                                $rating_label = 'V';
                                                            }
			                                             ?>
			                                             		<?php if ($cnt == 0) { ?>
			                                                        <div class="rating_label">
			                                                            <span>Rating(s)</span>
			                                                        </div>
			                                                        <?php $cnt++; ?>
			                                                    <?php } ?>
			                                                    <div class="wine_rate_box_combo wine_rate_box">
			                                                        <a href="/rating-guide">
			                                                        <span><?php echo strtoupper($rating_label); ?></span>
			                                                        <span><?php echo $_product->getAttributeText($Wine_rating."_low") . " - "; ?></span>
			                                                        <span><?php echo $_product->getAttributeText($Wine_rating); ?></span>
			                                                        </a>
			                                                    </div>
			                                            <?php } else { ?>
			                                                <?php if (null !== $_product->getCustomAttribute($Wine_rating)) { ?>
			                                                    <?php $rating_label = substr($Wine_rating, 0, strpos($Wine_rating, '_'));
			                                                    	if ($rating_label == 'wns') {
			                                            				$rating_label = 'w&s';
			                                            			}
			                                            			if ($rating_label == 'ag') {
		                                                                $rating_label = 'V';
		                                                            }
			                                                     ?>
			                                                    <?php if ($cnt == 0) { ?>
			                                                        <div class="rating_label">
			                                                            <span>Rating(s)</span>
			                                                        </div>
			                                                        <?php $cnt++; ?>
			                                                    <?php } ?>
			                                                        <div class="wine_rate_box">
			                                                        	<a href="/rating-guide">
			                                                            <span><?php echo $_product->getAttributeText($Wine_rating); ?></span>
			                                                            <span><?php echo strtoupper($rating_label); ?></span>
			                                                        	</a>
			                                                        </div>
			                                                <?php } ?>
			                                                    <?php if (null !== $_product->getCustomAttribute($Wine_rating."_low")) { ?>
			                                                        <?php $rating_label = substr($Wine_rating."_low", 0, strpos($Wine_rating."_low", '_')); ?>
			                                                        <?php if ($cnt == 0) { ?>
			                                                            <div class="rating_label">
			                                                                <span>Rating(s)</span>
			                                                            </div>
			                                                            <?php $cnt++; ?>
			                                                        <?php } ?>
			                                                        <div class="wine_rate_box">
			                                                        	<a href="/rating-guide">
			                                                            <span><?php echo $_product->getAttributeText($Wine_rating."_low"); ?></span>
			                                                            <span><?php echo strtoupper($rating_label); ?></span>
			                                                        	</a>
			                                                        </div>
			                                                    <?php } ?>
			                                            <?php } ?>
			                                       <?php } ?>
			                                    </div>
											</div>
										</div>
										<div class="product_price_info">
											<div class="price-availability-block clearfix">
												<?php if($stock_status != 4 && $stock_status != 1) {
													if ($_product->isAvailable()): ?>
														<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
													<?php else: ?>
														<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
													<?php endif;
												} ?>
											</div>
											<div class="product-item-inner">
												<?php if($product_price){ ?>
													<?php /* @noEscape */ echo $block->getProductPrice($_product); ?>
												<?php } ?>
												<div class="product_member_price">
												<?php if ($_product->getData('member_price')) { ?>
													<?php
													$member_price = $_product->getData('member_price');
													$member_price = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($member_price,true,false);
													$block_obj_custom = $this->getLayout()->createBlock('Winestop\Custom\Block\Customdata');
													$is_login = $block_obj_custom->isCustomerLoggedIn();
													?>
													<?php if ($is_login) { ?>
														<!-- <div class="product_member_price"> -->
															<div class="price_label">
																<span>Member Price: </span>
																<span><?php echo $member_price;?></span>
															</div>
														<!-- </div> -->
													<?php }else{ ?>
														<!-- <div class="product_member_price"> -->
															<div class="price_label not_login">
																<a href="/customer/account/login/"><span>Member Price</span></a>
															</div>
														<!-- </div> -->
													<?php } ?>
												<?php } ?>
												</div>
												<div class="availableqty">
													<?php
													$productId = $_product->getId();
													$qty = $productLabelHelper->getStockItem($productId);
													?>
													<?php if ($qty>0): ?>
													<label for="availableqty">Inventory : </label>
													<?php if ($qty > 24) : ?>
														<span><?php echo "24+"; ?></span>
													<?php else: ?>
														<span><?= $qty ?></span>
													<?php endif; ?>
													<?php else: ?>
														<label for="outofstock" class="outofstock">Inventory : </label>
														<span class="outofstock"><?php echo "Out of Stock"; ?></span>
													<?php endif;?>
												</div>
												<?php if (!$_product->isAvailable()){ ?>
													<div class="notify_me_button">
														<button type="button" title="Get Notified When Product Is In stock !!" class="action primary notify" id="<?php echo $_product->getId(); ?>">
									                        <span>
									                        	<a style="color: #fff;" href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>">Notify Me
																</a>
															</span>
									                    </button>
													</div>
													<div id="popup_modal_<?php echo $_product->getId(); ?>" style="display:none;">
																										<?php
														$Nblockobj = $this->getLayout()->createBlock("Webkul\OutOfStockNotification\Block\OutOfStockProduct");
														$allowedTypes = ['simple', 'configurable', 'virtual', 'downloadable'];
														$productModal = $_product;
														$productId = $_product->getData('entity_id');
														$productType = $_product->getData('type_id');
														if (in_array($productType, $allowedTypes)) {
															$stockStatus = $_product->isAvailable();
															$failureMsg = __("Please enter a valid email");
															$blankMsg = __("No email found");

															$customerEmail = $Nblockobj->getCustomerEmail();
															$fileUrl = $Nblockobj->getViewFileUrl('images/loader.gif');
															$action = $Nblockobj->getUrl('outofstocknotification/product/addcustomer');
															$actionConfig = $Nblockobj->getUrl('outofstocknotification/product/configproduct');

															if ($productType == 'configurable') {
																$stockStatus = $_product['stock'];
																$outOfStockAssociates = $_product['oosn_associates'];
																$outOfStockAssociatesString = implode(",", $outOfStockAssociates);
																if (!empty($outOfStockAssociatesString)) {
																	$title = __("Get Notified When Other Options (%1) Are Available !!", $outOfStockAssociatesString);
																	?>
																	<select  id="associate-select" class="" aria-required="true">
																		<option value="<?=$Nblockobj->escapeHtml($productId)?>">All out of stock options</option>
																		<?php

																		if (is_array($outOfStockAssociates) || is_object($outOfStockAssociates)) {
																			foreach ($outOfStockAssociates as $associateId => $assciate) {
																				?><option value="<?=$Nblockobj->escapeHtml($associateId)?>"><?=$Nblockobj->escapeHtml($assciate)?></option><?php
																			}}
																		} else {
																			$title = __("Get Notified When Product Is In stock !!");
																		}

																	} else {
																		$title = __("Get Notified When Product Is In stock !!");

																	}
																	?>
																	<input type="hidden" name="productId" value="<?= $Nblockobj->escapeHtml($productId); ?>">
																	<?php
																	$optionElements = [
																		'button' => '#wk-oosn-button',
																		'loader' => '.wk-loading-mask',
																		'email'    => 'email',
																		'productId' => $productId,
																		'stockStatus' => $stockStatus,
																		'action' => $action,
																		'productType' => $productType,
																		'actionConfig' => $actionConfig,
																		'form' => '.notificationForm',
																		'failureMsg' => $failureMsg,
																		'blankMsg' => $blankMsg,
																		'container' => '.wk-oosn-notificationcontainer',
																		'warning' => '#wk-oosn-warning',
																		'title' =>  $title
																	];
																	$serializedData = $Nblockobj->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($optionElements);

																	?>
																	<script type="text/x-magento-init">
																		{
																			"*":{
																			"notifyMe":<?= /* @noEscape */  $serializedData; ?>
																		}
																	}
																</script>

															<?php } ?>
													    <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Webkul_OutOfStockNotification::emailid.phtml")->toHtml() ?>
													</div>
												<?php } ?>
		                                    	<?php if ($_product->isSaleable() && $viewMode == 'list'){ ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php echo $block->escapeUrl($postParams['action']); ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey')?>
														<button type="submit"
																title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
																class="action tocart btn btn-default btn-cart">
															<i class="meigee-cart"></i>
															<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
														</button>
													</form>
											<?php } ?>
											<?php echo $this->getLayout()->createBlock(Magento\Framework\View\Element\Template::class)->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_product)->toHtml(); ?>
											</div>
										</div>
									</div>
								</div>
							</div>
						</li>
					<?php endforeach; ?>
				<?php } else { ?>
					<?php foreach ($_productCollection as $_product): ?>
						<li class="item product product-item">
						<div class="product-item-info clearfix<?php echo !$_product->isAvailable() ? ' sold-out' : ''; ?>" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
							<div class="indent product-hover-1">
								<div class="image-wrapper">
									<?php
									$hoverImage = $image_hover_status ? $_product->getHoverImage() : false;
									$productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>null));

									if ($pos != null) {
										$position = ' style="left:' . $productImage->getWidth() . 'px;'
											. 'top:' . $productImage->getHeight() . 'px;"';
									} ?>
									<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
										<?php echo $productImage->toHtml(); ?>
									</a>
		                            <?php
		                            	$is_bestseller = false;
										if ($_product->getData('special_designations')) {
			                                $spe = explode(",", $_product->getData('special_designations'));
			                                if (in_array('44',$spe)) {
			                                    $is_bestseller = true;
			                                }
			                            }
		                                if($front_helper->isProductNew($_product) || $front_helper->isProductSale($_product) || $front_helper->isProductOnlyLeft($_product) || $is_bestseller){
		                                    echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_product) && $front_helper->isProductSale($_product)) || ($front_helper->isProductNew($_product) && $front_helper->isProductOnlyLeft($_product)) ? ' two-items' : '').'">';
		                                        
		                                        if ($front_helper->isProductOnlyLeft($_product) && $label_sale) {
		                                            echo $front_helper->isProductOnlyLeft($_product);
		                                        }
		                                        elseif($front_helper->getProductSalePercent($_product) && $label_sale) {
		                                            echo $front_helper->getProductSalePercent($_product);
		                                        } elseif ($front_helper->isProductSale($_product) && $label_sale) {
		                                            echo '<span class="label-sale">'.__('sale').'</span>';
		                                        }
		                                    echo '</div>';
		                                }
		                            ?>
		                            <div class="hover-buttons">
			                            <?php if($lightbox_status && $lightbox_listing_status){ ?>
			                                <a href="<?php echo $this->getUrl() . 'pub/media/catalog/product/' .$_product->getData('thumbnail');  ?>" class="lightbox-button"  data-toggle="lightbox" data-footer="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" title="<?php echo __('Lightbox'); ?>">
			                                    <i class="meigee-zoom"></i>
			                                </a>
			                            <?php } ?>
	                                    <?php if($compare_btn || $wishlist_btn){ ?>
	                                        <div data-role="add-to-links" class="add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
	                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
	                                                <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
	                                            <?php endif; ?>
	                                        </div>
	                                    <?php } ?>
			                            <?php if($quickview_btn && $quickview_status) { ?>
			                                <a href="javascript: void(0);" data-quickview-url="<?php echo $block->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_product->getEntityId()); ?>" class="weltpixel-quickview"><i class="meigee-fa-eye"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
			                            <?php } ?>
			                            <?php if($cart_btn){ ?>
			                                <div class="product-action-wrapper">
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php echo $block->escapeUrl($postParams['action']); ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey')?>
														<button type="submit"
																title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
																class="action tocart btn btn-default btn-cart">
															<i class="meigee-cart"></i>
															<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
														</button>
													</form>
												<?php else: ?>
													<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
												<?php endif; ?>
			                                </div>
			                            <?php } ?>
		                            </div>
		                            <?php if (!$_product->isAvailable()): ?>
		                                <div class="sold-out-label">
		                                    <span><?php /* @escapeNotVerified */ echo __('Out Of Stock') ?></span>
		                                </div>
		                            <?php endif; ?>
								</div>
								<div class="product details product-item-details">
		                            <?php if($product_name){
		                                $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
		                                <h4 class="product name product-item-name <?php echo $name_align; ?>">
		                                    <a class="product-item-link"
		                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
		                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
		                                    </a>
		                                </h4>
		                            <?php }
		                            if($stock_status != 4 && $stock_status != 2) {
		                                if ($_product->isAvailable()): ?>
		                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
		                                <?php else: ?>
		                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
		                               <?php endif;
		                            }

		                                echo $block->getReviewsSummaryHtml($_product, $templateType);
		                             ?>
		                            <div class="product-item-inner">
		                                 <?php if ($showDescription && $_product->getShortDescription()):?>
		                                    <div class="product description product-item-description">
		                                        <?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
		                                        <a href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>" title="<?php /* @noEscape */ echo $_productNameStripped ?>"
		                                           class="action more"><?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Learn More')) ?></a>
		                                    </div>
		                                <?php endif; ?>
		                            <div class="swatches-wrapper">
		                                <?php echo $block->getProductDetailsHtml($_product); ?>
		                            </div>
		                            <?php if($product_price){ ?>
		                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product); ?>
		                            <?php } ?>
	                                    <?php
                                        		//labels start
		                                        $specialArr = [];
		                                        $newProduct = $productLabelHelper->isNewArrival($_product);
		                                            if($newProduct){
		                                                $specialArr['New Arrival']=$newProduct;
		                                            }
		                                        ?>
		                                        <?php
		                                        $specialAssignment = $productLabelHelper->getSpecialAttribute($_product);
		                                        if ($specialAssignment) {
		                                            foreach ($specialAssignment as $key => $assignValue) {
		                                                if($newProduct) {
		                                                    if ($assignValue) {
		                                                        $className = $productLabelHelper->getClassName($assignValue); 
		                                                        $specialArr[$className]=$assignValue;
		                                                        break;
		                                                    }
		                                                }else{
		                                                    if($key>1){
		                                                        break;
		                                                    }
		                                                    if ($assignValue) {
		                                                        $className = $productLabelHelper->getClassName($assignValue); 
		                                                        $specialArr[$className]=$assignValue;
		                                                    }
		                                                }
		                                            }
		                                        }
		                                       // if(count($specialArr)):?>
		                                       	<div class="product_member_price">
					                            	<?php if ($_product->getData('member_price')) { ?>
				                                        <?php
				                                        $member_price = $_product->getData('member_price');
				                                        $member_price = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($member_price,true,false);
				                                        $block_obj_custom = $this->getLayout()->createBlock('Winestop\Custom\Block\Customdata');
				                                        $is_login = $block_obj_custom->isCustomerLoggedIn();
				                                        ?>
				                                        <?php if ($is_login) { ?>
				                                            <!-- <div class="product_member_price"> -->
				                                                <div class="price_label">
				                                                    <span>Member Price: </span>
				                                                    <span><?php echo $member_price; ?></span>
				                                                </div>
				                                            <!-- </div> -->
				                                        <?php }else{ ?>
				                                            <!-- <div class="product_member_price"> -->
				                                                <div class="price_label not_login">
				                                                    <a href="/customer/account/login/"><span>Member Price</span></a>
				                                                </div>
				                                            <!-- </div> -->
				                                        <?php } ?>
				                                    <?php } ?>
	                                			</div>
		                                            <div class="labels">
		                                                <?php foreach ($specialArr as $className => $_assignValue) :?>
		                                                    <label for="<?=($className=='New Arrival')?'newarrival':'specialattribute'?>">
		                                                        <span class="<?=($className=='New Arrival')?'newarrival':$className ?>">
		                                                            <img class="white-icon" src="<?php echo $this->getViewFileUrl('images/'.$className.'.png'); ?>" alt="<?php $_assignValue ?>" height="auto">
		                                                        </span>
		                                                    </label>
		                                                <?php endforeach;?>
		                                            </div>
		                                        <?php //endif;?>
		                                        <?php //labels end ?>
	                                    <?php
	                                        $all_wine_rating = array("ag_rating", "bh_rating", "cg_rating","gr_rating","jd_rating",
	                                                      "jh_rating","js_rating","pr_rating","rp_rating","st_rating",
	                                                      "wa_rating","we_rating","wns_rating","wn_rating","ws_rating","d_rating","sk_rating","jg_rating");
	                                        $cnt = 0;
	                                    ?>
	                                    <div class="wine_rating_block">
			                                       <?php foreach($all_wine_rating as $Wine_rating) { ?>
			                                            <?php if (null !== $_product->getCustomAttribute($Wine_rating) && null !== $_product->getCustomAttribute($Wine_rating."_low")) {
			                                            	$rating_label = substr($Wine_rating, 0, strpos($Wine_rating, '_'));
			                                            	if ($rating_label == 'wns') {
			                                            		$rating_label = 'w&s';
			                                            	}
			                                            	if ($rating_label == 'ag') {
                                                                $rating_label = 'V';
                                                            }
			                                             ?>
			                                             		<?php if ($cnt == 0) { ?>
			                                                        <div class="rating_label">
			                                                            <span>Rating(s)</span>
			                                                        </div>
			                                                        <?php $cnt++; ?>
			                                                    <?php } ?>
			                                                    <div class="wine_rate_box_combo wine_rate_box">
			                                                        <a href="/rating-guide">
			                                                        <span><?php echo strtoupper($rating_label); ?></span>
			                                                        <span><?php echo $_product->getAttributeText($Wine_rating."_low") . " - "; ?></span>
			                                                        <span><?php echo $_product->getAttributeText($Wine_rating); ?></span>
			                                                        </a>
			                                                    </div>
			                                            <?php } else { ?>
			                                                <?php if (null !== $_product->getCustomAttribute($Wine_rating)) { ?>
			                                                    <?php $rating_label = substr($Wine_rating, 0, strpos($Wine_rating, '_'));
			                                                    	if ($rating_label == 'wns') {
			                                            				$rating_label = 'w&s';
			                                            			}
			                                            			if ($rating_label == 'ag') {
		                                                                $rating_label = 'V';
		                                                            }
			                                                     ?>
			                                                    <?php if ($cnt == 0) { ?>
			                                                        <div class="rating_label">
			                                                            <span>Rating(s)</span>
			                                                        </div>
			                                                        <?php $cnt++; ?>
			                                                    <?php } ?>
			                                                        <div class="wine_rate_box">
			                                                        	<a href="/rating-guide">
			                                                            <span><?php echo $_product->getAttributeText($Wine_rating); ?></span>
			                                                            <span><?php echo strtoupper($rating_label); ?></span>
			                                                        	</a>
			                                                        </div>
			                                                <?php } ?>
			                                                    <?php if (null !== $_product->getCustomAttribute($Wine_rating."_low")) { ?>
			                                                        <?php $rating_label = substr($Wine_rating."_low", 0, strpos($Wine_rating."_low", '_')); ?>
			                                                        <?php if ($cnt == 0) { ?>
			                                                            <div class="rating_label">
			                                                                <span>Rating(s)</span>
			                                                            </div>
			                                                            <?php $cnt++; ?>
			                                                        <?php } ?>
			                                                        <div class="wine_rate_box">
			                                                        	<a href="/rating-guide">
			                                                            <span><?php echo $_product->getAttributeText($Wine_rating."_low"); ?></span>
			                                                            <span><?php echo strtoupper($rating_label); ?></span>
			                                                        	</a>
			                                                        </div>
			                                                    <?php } ?>
			                                            <?php } ?>
			                                       <?php } ?>
			                                    </div>
			                                    <div class="availableqty">
													<?php
													$productId = $_product->getId();
													$qty = $productLabelHelper->getStockItem($productId);
													?>
													<?php if ($qty>0): ?>
													<label for="availableqty">Inventory : </label>
													<?php if ($qty > 24) : ?>
														<span><?php echo "24+"; ?></span>
													<?php else: ?>
														<span><?= $qty ?></span>
													<?php endif; ?>
													<?php else: ?>
														<label for="outofstock" class="outofstock">Inventory : </label>
														<span class="outofstock"><?php echo "Out of Stock"; ?></span>
													<?php endif;?>
												</div>
	                                    <?php if (!$_product->isAvailable()){ ?>
													<div class="notify_me_button">
														<button type="button" title="Get Notified When Product Is In stock !!" class="action primary tocart" id="notify_me">
									                        <a style="color: #fff;" href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>">Notify Me
																</a>
									                    </button>
													</div>
													<div id="popup-modal" style="display:none;">
																										<?php
														$Nblockobj = $this->getLayout()->createBlock("Webkul\OutOfStockNotification\Block\OutOfStockProduct");
														$allowedTypes = ['simple', 'configurable', 'virtual', 'downloadable'];
														$productModal = $_product;
														$productId = $_product->getData('entity_id');
														$productType = $_product->getData('type_id');
														if (in_array($productType, $allowedTypes)) {
															$stockStatus = $_product->isAvailable();
															$failureMsg = __("Please enter a valid email");
															$blankMsg = __("No email found");

															$customerEmail = $Nblockobj->getCustomerEmail();
															$fileUrl = $Nblockobj->getViewFileUrl('images/loader.gif');
															$action = $Nblockobj->getUrl('outofstocknotification/product/addcustomer');
															$actionConfig = $Nblockobj->getUrl('outofstocknotification/product/configproduct');

															if ($productType == 'configurable') {
																$stockStatus = $_product['stock'];
																$outOfStockAssociates = $_product['oosn_associates'];
																$outOfStockAssociatesString = implode(",", $outOfStockAssociates);
																if (!empty($outOfStockAssociatesString)) {
																	$title = __("Get Notified When Other Options (%1) Are Available !!", $outOfStockAssociatesString);
																	?>
																	<select  id="associate-select" class="" aria-required="true">
																		<option value="<?=$Nblockobj->escapeHtml($productId)?>">All out of stock options</option>
																		<?php

																		if (is_array($outOfStockAssociates) || is_object($outOfStockAssociates)) {
																			foreach ($outOfStockAssociates as $associateId => $assciate) {
																				?><option value="<?=$Nblockobj->escapeHtml($associateId)?>"><?=$Nblockobj->escapeHtml($assciate)?></option><?php
																			}}
																		} else {
																			$title = __("Get Notified When Product Is In stock !!");
																		}

																	} else {
																		$title = __("Get Notified When Product Is In stock !!");

																	}
																	?>
																	<input type="hidden" name="productId" value="<?= $Nblockobj->escapeHtml($productId); ?>">
																	<?php
																	$optionElements = [
																		'button' => '#wk-oosn-button',
																		'loader' => '.wk-loading-mask',
																		'email'    => 'email',
																		'productId' => $productId,
																		'stockStatus' => $stockStatus,
																		'action' => $action,
																		'productType' => $productType,
																		'actionConfig' => $actionConfig,
																		'form' => '.notificationForm',
																		'failureMsg' => $failureMsg,
																		'blankMsg' => $blankMsg,
																		'container' => '.wk-oosn-notificationcontainer',
																		'warning' => '#wk-oosn-warning',
																		'title' =>  $title
																	];
																	$serializedData = $Nblockobj->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($optionElements);

																	?>
																	<script type="text/x-magento-init">
																		{
																			"*":{
																			"notifyMe":<?= /* @noEscape */  $serializedData; ?>
																		}
																	}
																</script>

															<?php } ?>
													    <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Webkul_OutOfStockNotification::emailid.phtml")->toHtml() ?>
													</div>
										<?php } ?>
	                                    <?php if ($_product->isSaleable()){ ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php echo $block->escapeUrl($postParams['action']); ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey')?>
														<button type="submit"
																title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
																class="action tocart btn btn-default btn-cart">
															<i class="meigee-cart"></i>
															<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
														</button>
													</form>
										<?php } ?>
		                            <?php echo $this->getLayout()->createBlock(Magento\Framework\View\Element\Template::class)->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_product)->toHtml(); ?>
									</div>
								</div>
							</div>
						<?php if($_product->isAvailable()){ ?>
						</li>
						<?php } ?>
					<?php endforeach; ?>
				<?php } ?>
	        </ol>
	    </div>
		<div class="toolbar-bottom">
			<?php echo $block->getToolbarHtml() ?>
		</div>
</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
   <script type="text/javascript">
require(['jquery'], function ($)
{

	jQuery(document).ready(function(){
		function listingBanner() {
			if(jQuery('.category-description .listing-banner').length){
				var mode = jQuery('.listing-banner').data('mode');
				var position = jQuery('.listing-banner').data('position');
				var rowPosition = jQuery('.listing-banner').data('rowPosition');
				banner1 = jQuery('.listing-banner');
				if(jQuery('.listing-banner-wrapper').length == 0) {
					banner = banner1.clone();
					banner = banner.wrap("<li class='item listing-banner-wrapper'></li>");
					banner.parent().hide();
					if(!jQuery('.category-description').find('.listing-banner-wrapper').length) {
						banner.parent().appendTo(jQuery('.category-description'));
					}
				}
				switch (mode){
					case 'grid':
						if(jQuery('.products.products-grid').length){
							banner.parent().show();
							jQuery('.products-grid').parents('.main-container').find('.category-description li.item').css('display', 'block');
							if (rowPosition == 1) {
								rowPosition = 2;
							}
							if (rowPosition) {
								columns=1;
								if (jQuery(document.body).width() >= 375 && jQuery(document.body).width() <= 767) {
									columns = 2;
								} else if (jQuery(document.body).width() < 375) {
									columns = 1;
								} else if (jQuery(document.body).width() >= 768 && jQuery(document.body).width() <= 1007) {
									columns = 3;
								} else if (jQuery(document.body).width() >= 1008) {
									if (jQuery('.products-grid').hasClass('eight-columns')) {
										columns = 8;
									} else if (jQuery('.products-grid').hasClass('seven-columns')) {
										columns = 7;
									} else if (jQuery('.products-grid').hasClass('six-columns')) {
										columns = 6;
									} else if (jQuery('.products-grid').hasClass('five-columns')) {
										columns = 5;
									} else if (jQuery('.products-grid').hasClass('four-columns')) {
										columns = 4;
									} else if (jQuery('.products-grid').hasClass('three-columns')) {
										columns = 3;
									} else if (jQuery('.products-grid').hasClass('two-columns')) {
										columns = 2;
									}
								}

								if (jQuery(document.body).width() >= 1008 && jQuery(document.body).width() <= 1331
									&& (columns == 8 || columns == 7 || columns == 6)
									&& (jQuery('.main-container').hasClass('col2-left-layout') || jQuery('.main-container').hasClass('col2-right-layout'))) {
										columns = 5;
								}

								if(jQuery('.products-grid').find('li.listing-banner-wrapper').length == 0) {
									jQuery('.products-grid li.item:nth-of-type(' + columns*(rowPosition-1) + ')').after(jQuery('.category-description .listing-banner-wrapper').addClass('row-banner'));
								}
							} else {
								if(jQuery('.products-grid li.listing-banner-wrapper').length == 0) {
									jQuery('.products-grid li.item:nth-of-type(' + (position-1) + ')').after(jQuery('.category-description .listing-banner-wrapper'));
								}
							}
						}
					break;
					case 'list':
						if(jQuery('.products.products-list').length){
							if(jQuery('.products-list li.listing-banner-wrapper').length == 0) {
								banner.parent().show();
								jQuery('.products-list').parents('.main-container').find('.category-description li.item').css('display', 'block');
								jQuery('.products-list li.item:nth-of-type(' + (position-1) + ')').after(jQuery('.listing-banner-wrapper'));
							}
						}
					break;
				}
			}
		}
		function moveListingBanner () {
		    if (jQuery('.products-grid .listing-banner-wrapper').length) {
		        rowPosition = jQuery('.products-grid .listing-banner-wrapper .listing-banner').data('rowPosition');
		        if (rowPosition) {
		            columns=1;
		            if (jQuery(document.body).width() >= 375 && jQuery(document.body).width() <= 767) {
		                columns = 2;
		            } else if (jQuery(document.body).width() < 375) {
		                columns = 1;
		            } else if (jQuery(document.body).width() >= 768 && jQuery(document.body).width() <= 1007) {
		                columns = 3;
		            } else if (jQuery(document.body).width() >= 1008) {
		                if (jQuery('.products-grid').hasClass('eight-columns')) {
		                    columns = 8;
		                } else if (jQuery('.products-grid').hasClass('seven-columns')) {
		                    columns = 7;
		                } else if (jQuery('.products-grid').hasClass('six-columns')) {
		                    columns = 6;
		                } else if (jQuery('.products-grid').hasClass('five-columns')) {
		                    columns = 5;
		                } else if (jQuery('.products-grid').hasClass('four-columns')) {
		                    columns = 4;
		                } else if (jQuery('.products-grid').hasClass('three-columns')) {
		                    columns = 3;
		                } else if (jQuery('.products-grid').hasClass('two-columns')) {
		                    columns = 2;
		                }
		            }

		            if (jQuery(document.body).width() >= 1008 && jQuery(document.body).width() <= 1331
		                && (columns == 8 || columns == 7 || columns == 6)
		                && (jQuery('.main-container').hasClass('col2-left-layout') || jQuery('.main-container').hasClass('col2-right-layout'))) {
		                    columns = 5;
		            }
		            banner = jQuery('.listing-banner-wrapper').remove();
		            jQuery('.products-grid li.item:not(.listing-banner-wrapper):nth-of-type(' + columns*(rowPosition-1) + ')').after(banner);
		        }
		    }
		}
		listingBanner();
	    jQuery(window).resize(function() {
	        moveListingBanner();
	    });

	    <?php if($listingCustomGrid == 1 ): ?>
            require(['jquery', 'meigeeCookies'], function ()
            {
                jQuery(window).bind('unload', function(e) {
                    console.log(e);
                    console.log(window.event);
                    var evt = e || window.event;
                    if (evt.clientX < 0 && evt.clientY < 0){
                        jQuery.removeCookie('barbourListingGridSwitcher', { path: '/' });
                    }
                });
                var listingGrid = jQuery.cookie('barbourListingGridSwitcher');
                var productLists = jQuery('.products.wrapper.products-grid');
                var classesProductLists = ["one-column", "two-columns", "three-columns", "four-columns", "five-columns", "six-columns", "seven-columns", "eight-columns"];
                /*function listingGridCookie(){
                    jQuery.cookie('barbourListingGridSwitcher', '<?php echo $grid_columns ?>', {
                        expires: null,
                        path: '/'
                    });
                }*/
                function listingGridSwitch(){
                    jQuery.each(classesProductLists, function(i, v){
                        jQuery(productLists).removeClass(v);
                    });
                    jQuery(productLists).addClass(jQuery.cookie('barbourListingGridSwitcher'));
                    listingBanner();
                    moveListingBanner();
                }
                /*if(!(listingGrid)){
                    jQuery.cookie('barbourListingGridSwitcher', '<?php echo $grid_columns ?>', {
                        expires: null,
                        path: '/'
                    });
                }*/

                jQuery('.modes span.item').on('click', function(){
                    jQuery('.product-items .item').removeClass('hovered');
                    if (!jQuery(this).hasClass('current')) {
                        jQuery('.toolbar .modes span.item').removeClass('current');
                        jQuery(this).addClass('current');
                        jQuery.removeCookie('barbourListingGridSwitcher', null);
                        jQuery.cookie('barbourListingGridSwitcher', jQuery(this).data('grid-swither'), {
                            expires: null,
                            domain: window.location.host,
                            path: '/'
                        });
                        listingGridSwitch();
                    }
                });


            });
        <?php endif; ?>
	});
});

</script>
<?php endif; ?>
<script type="text/javascript">
	require(['jquery', 'jquery/ui'], function($){
		$(document).ready(function () {
			var old_url = document.location.href;
			var index = old_url.indexOf('?');
			if (index == -1) {
				var symb = '?'
			}else{
				var symb = '&'
			}
			$(".include_ot_of_stock").change(function() {
				if(this.checked) {
					var old_url = document.location.href;
					var lastChar = old_url[old_url.length -1];
					if (lastChar == '#' || lastChar == '?' || lastChar == '&') {
						old_url = old_url.slice(0,-1);
					}
					var url = old_url+symb+"show-out-of-stock=1";
      				document.location = url;
        		}else{
					var old_url = document.location.href;
					var new_url = removeURLParameter(old_url, 'show-out-of-stock');
					var lastChar = new_url[new_url.length -1];
					if (lastChar == '?' || lastChar == '&' || lastChar == '#') {
						new_url = new_url.slice(0,-1);
					}
					document.location = new_url;
        		}
			});
			var show_outof_stock = getUrlParameter('show-out-of-stock');
			if (show_outof_stock) {
				$(".include_ot_of_stock").prop("checked", true);
			}
			function getUrlParameter(sParam) {
				var sPageURL = window.location.search.substring(1),
				sURLVariables = sPageURL.split('&'),
				sParameterName,
				i;

				for (i = 0; i < sURLVariables.length; i++) {
					sParameterName = sURLVariables[i].split('=');

					if (sParameterName[0] === sParam) {
						return sParameterName[1] === undefined ? true : decodeURIComponent(sParameterName[1]);
					}
				}
			};
			function removeURLParameter(url, parameter) {
			    //prefer to use l.search if you have a location/link object
			    var urlparts= url.split('?');
			    if (urlparts.length>=2) {

			    	var prefix= encodeURIComponent(parameter)+'=';
			    	var pars= urlparts[1].split(/[&;]/g);

			        //reverse iteration as may be destructive
			        for (var i= pars.length; i-- > 0;) {
			            //idiom for string.startsWith
			            if (pars[i].lastIndexOf(prefix, 0) !== -1) {
			            	pars.splice(i, 1);
			            }
			        }

			        url= urlparts[0]+'?'+pars.join('&');
			        return url;
			    } else {
			    	return url;
			    }
			}
		});
	});
</script>
<script type="text/javascript">
	require(
		[
		'jquery',
		'Magento_Ui/js/modal/modal'
		],
		function(
			$,
			modal
			) {
			var options = {
				type: 'popup',
				responsive: true,
				innerScroll: true,
				title: 'Notify Me',
				modalClass: 'notifu_me_popup_model',
				buttons: []
			};

			$(".notify").on('click',function(){
				var current_id = $(this).attr('id');
				var popup = modal(options, $('#popup_modal_' + current_id));
				$('#wk-oosn-warning').css('display','none');
				$("#popup_modal_" + current_id).modal("openModal");
			});

		}
	);
</script>
<script type="text/javascript">
	require(['jquery', 'jquery/ui'], function($){
		jQuery(document).ready(function(){
			$(function(){
				var minimized_elements = $('.product-item-description');

				minimized_elements.each(function(){
					var t = $(this).text();
					if(t.length > 400) {
						$(this).html(t.slice(0,400));
					}
					var product_url = $(this).attr('data-url');
					var product_name = $(this).attr('data-title');
					var learn_more_tag = '<a href="'+product_url+'" class="action more" title="'+product_name+'">Learn More</a>';
					$(learn_more_tag).appendTo($(this));
					// add learn more text
				});
			});
		});
	});
</script>
<div class="temp_pro_list" style="display: none;">
	
</div>