<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Framework\View\Element\Template */
$results = $block->getTrackingInfo();
if (!empty($results)){
    foreach ($results as $shipId => $result) {
        foreach ($result as $counter => $track) {
            if ($track['title'] == 'Golden State Overnight') {
                $trackingNumber = $track['number'];
            }
        }
    }
}
$helper = $this->helper('Winestop\Gso\Helper\Data');
//$trackingNumber = '875783000013871'; //0910202012
$response = $helper->getGsoTrackShipment($trackingNumber);
$response = (array) json_decode($response);
?>
<?php if ($response['StatusCode'] == 200) { ?>
    <div class="table-wrapper">
        <table class="data table order tracking" id="track-history-table-<?= $block->escapeHtml($trackingNumber) ?>">
            <caption class="table-caption"><?= $block->escapeHtml(__('Track history')) ?></caption>
            <thead>
            <tr>
                <th class="col location" scope="col"><?= $block->escapeHtml(__('Location')) ?></th>
                <th class="col date" scope="col"><?= $block->escapeHtml(__('Date')) ?></th>
                <th class="col time" scope="col"><?= $block->escapeHtml(__('Local Time')) ?></th>
                <th class="col description" scope="col"><?= $block->escapeHtml(__('Description')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
                $shipmentinfo = $response['ShipmentInfo'];
            ?>
            <?php foreach ($shipmentinfo as $detail) : ?>
                <?php $detail = (array) $detail ?>
                <?php 
                 $transitNotes =  array_reverse($detail['TransitNotes']); 
                ?>
                <?php foreach ($transitNotes as $data) : ?>
                    <?php $data = (array) $data ?>
                    <?php 
                        $date = strtotime($data['EventDate']);
                        $detailDate = date('d-M-Y', $date);
                        $detailTime = date('h:i:s', $date);
                    ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Location')) ?>" class="col location">
                            <?= (!empty($data['Location']) ? $block->escapeHtml($data['Location']) : '') ?>
                        </td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="col date">
                            <?= /* @noEscape */ $detailDate ?>
                        </td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Local Time')) ?>" class="col time">
                            <?= /* @noEscape */ $detailTime ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Description')) ?>" class="col description">
                            <?= (!empty($data['Comments']) ? $block->escapeHtml($data['Comments']) : '') ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php } ?>
