<?php
$handle = $this->getLayout()->getUpdate()->getHandles();
if(!in_array('onestepcheckout_index_index',$handle)){
?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Begin Constant Contact Active Forms -->
<script> var _ctct_m = "f1ab5c203618172db5f2a33eb4bf5fc2"; </script>
<script id="signupScript" src="//static.ctctcdn.com/js/signup-form-widget/current/signup-form-widget.min.js" async defer></script>
<!-- End Constant Contact Active Forms -->
<?php } ?>
<script type='text/javascript'>
  window.smartlook||(function(d) {
    var o=smartlook=function(){ o.api.push(arguments)},h=d.getElementsByTagName('head')[0];
    var c=d.createElement('script');o.api=new Array();c.async=true;c.type='text/javascript';
    c.charset='utf-8';c.src='https://web-sdk.smartlook.com/recorder.js';h.appendChild(c);
    })(document);
    smartlook('init', '42408150498406ad70902f9861a26056c8db6356', { region: 'eu' });
</script>