<?php
/**
 * Copyright © Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
 // phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php echo $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
	$meigee_helper = $this->helper(\Meigee\Barbour\Helper\BarbourGeneral::class);
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        // $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
		$grid_columns = $lightbox_status = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'grid_columns');
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        // $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		$grid_columns = '';
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
	$lightbox_status = $meigee_helper->getCustomThemeOptionCnf('barbour_lightbox', 'lightbox_status');
	$lightbox_listing_status = $meigee_helper->getCustomThemeOptionCnf('barbour_lightbox', 'lightbox_listing');
	$product_name = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'product_name');
	$product_price = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'product_price');
	$cart_btn = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'cart_btn');
	$compare_btn = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'compare_btn');
	$wishlist_btn = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'wishlist_btn');
	$name_align = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'product_name_aligment');
	$stock_status = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'stock_status');
    $image_hover_status = $meigee_helper->getCustomThemeOptionCnf('barbour_image_hover', 'image_hover_status');
    $image_hover_effect = $meigee_helper->getCustomThemeOptionCnf('barbour_image_hover', 'image_hover_type');
	$quickview_status = $this->helper('WeltPixel\Quickview\Helper\Data')->getConfig('weltpixel_quickview/general/enable_product_listing');
	$quickview_btn = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'quickview_btn');
    $front_helper = $this->helper(\Meigee\Barbour\Helper\FrontHelper::class);

    $labels_type = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_type');
    $label_new = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_new');
    $label_sale = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_sale');
    $label_sale_percentage = $meigee_helper->getCustomThemeOptionCnf('barbour_labels', 'label_sale_percentage');
	
	$listingCustomGrid = $meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'listing_custom_grid');
    $listingColumnsGridString = preg_replace('/\s+/','',$meigee_helper->getCustomThemeOptionCnf('barbour_product_listing', 'listing_grid_switcher'));
    $listingColumnsGrids = explode(',', $listingColumnsGridString);
    $_columns = array(
        '1' => 'one-column',
        '2' => 'two-columns',
        '3' => 'three-columns',
        '4' => 'four-columns',
        '5' => 'five-columns',
        '6' => 'six-columns',
        '7' => 'seven-columns',
        '8' => 'eight-columns'
    );
    $_columnsSet = array();
    foreach ($listingColumnsGrids as $_key => $_listingColumnsGrid) {
      array_push($_columnsSet, $_columns[$_listingColumnsGrid]);
    }
    array_push($_columnsSet, 'one-column');
    array_push($_columnsSet, 'two-columns');
    $listingCustomGridCookie = $front_helper->getFrontCookie('barbourListingGridSwitcher');

    if ($listingCustomGrid == 1) {
        if ($listingCustomGridCookie) {
            if(in_array($listingCustomGridCookie,$_columnsSet) == false){
                $grid_columns = $_columns[array_shift($listingColumnsGrids)];
            } else {
                $grid_columns = $listingCustomGridCookie;
            }
        } else {
            $grid_columns = $_columns[array_shift($listingColumnsGrids)];
        }
    }
    ?>
    <div class="products wrapper <?php /* @noEscape */ echo $viewMode; ?> products-<?php /* @noEscape */ echo $viewMode .' '. $grid_columns; if($image_hover_status){echo $image_hover_effect ? ' hover-scale' : ' hover-simple';} ?>">
        <ol class="products clearfix list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>

			<?php if($viewMode == 'list') { ?>
				 <?php foreach ($_productCollection as $_product): ?>
					<li class="item product product-item">
						<div class="product-item-info clearfix<?php echo !$_product->isAvailable() ? ' sold-out' : ''; ?>" data-container="product-<?= /* @noEscape */ $viewMode ?>">
							<div class="indent product-hover-1">
								<div class="image-wrapper">
									<?php
									$hoverImage = $image_hover_status ? $_product->getHoverImage() : false;
									if ($hoverImage)
									{
										$hoverImageUrl = $this->helper(Magento\Catalog\Helper\Image::class)
														  ->init($_product, 'hover_image')
														  ->setImageFile($hoverImage)
														  ->getUrl();
										$productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>$hoverImageUrl));
									}
									else
									{
										$productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>null));
									}

									if ($pos != null) {
										$position = ' style="left:' . $productImage->getWidth() . 'px;'
											. 'top:' . $productImage->getHeight() . 'px;"';
									} ?>
									<?php
										if($front_helper->isProductNew($_product) || $front_helper->isProductSale($_product) || $front_helper->isProductOnlyLeft($_product)){
											echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_product) && $front_helper->isProductSale($_product)) || ($front_helper->isProductNew($_product) && $front_helper->isProductOnlyLeft($_product)) ? ' two-items' : '').'">';
												if($front_helper->isProductNew($_product) && $label_new) {
													echo '<span class="label-new">'.__('new').'</span>';
												}
												if ($front_helper->isProductOnlyLeft($_product) && $label_sale) {
													echo $front_helper->isProductOnlyLeft($_product);
												}
												elseif($front_helper->getProductSalePercent($_product) && $label_sale) {
													echo $front_helper->getProductSalePercent($_product);
												} elseif ($front_helper->isProductSale($_product) && $label_sale) {
													echo '<span class="label-sale">'.__('sale').'</span>';
												}
											echo '</div>';
										}
									?>
									<div class="hover-buttons">
										<?php if($lightbox_status && $lightbox_listing_status){ ?>
											<a href="<?php echo $productImage->getImageUrl();  ?>" class="lightbox-button"  data-toggle="lightbox" data-footer="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" title="<?php echo __('Lightbox'); ?>">
												<i class="meigee-zoom"></i>
											</a>
										<?php } ?>		                            
										<?php if($compare_btn || $wishlist_btn){ ?>
											<div data-role="add-to-links" class="add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
												<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
													<?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
												<?php endif; ?>
											</div>
										<?php } ?>	                            	
										<?php if($quickview_btn && $quickview_status) { ?>
											<a href="javascript: void(0);" data-quickview-url="<?php echo $block->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_product->getEntityId()); ?>" class="weltpixel-quickview"><i class="meigee-fa-eye"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
										<?php } ?>		                            
										<?php if($cart_btn){ ?>
											<div class="product-action-wrapper">
												<?php if ($_product->isSaleable()): ?>
													<?php $postParams = $block->getAddToCartPostParams($_product); ?>
													<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php echo $block->escapeUrl($postParams['action']); ?>" method="post">
														<input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
														<input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
														<?php echo $block->getBlockHtml('formkey')?>
														<button type="submit"
																title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
																class="action tocart btn btn-default btn-cart">
															<i class="meigee-cart"></i>
															<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
														</button>
													</form>
												<?php else: ?>
													<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
												<?php endif; ?>
											</div>
										<?php } ?>
									</div>
									<?php

									// Product Image ?>

									<a href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
										<?php echo $productImage->toHtml(); ?>
									</a>
										<?php if (!$_product->isAvailable()): ?>
											<div class="sold-out-label">
												<span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
											</div>
										<?php endif; ?>

								</div>
								<div class="product details product-item-details">
									<?php if($product_name){
										$_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
										<h4 class="product name product-item-name <?php echo $name_align; ?>">
											<a class="product-item-link"
											   href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>">
												<?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
											</a>
										</h4>
									<?php } ?>
									<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
									<div class="price-availability-block clearfix">
										<?php if($stock_status != 4 && $stock_status != 1) {
											if ($_product->isAvailable()): ?>
												<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
											<?php endif;
										} ?>
									</div>
									<div class="product-item-inner">
										 <?php if ($showDescription):?>
											<div class="product description product-item-description">
												<?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
												<a href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>" title="<?php /* @noEscape */ echo $_productNameStripped ?>"
												   class="action more"><?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Learn More')) ?></a>
											</div>
										<?php endif; ?>

										<div class="swatches-wrapper">
											<?php echo $block->getProductDetailsHtml($_product); ?>
										</div>
										<?php if($product_price){ ?>
											<?php /* @noEscape */ echo $block->getProductPrice($_product); ?>
										<?php } ?>
										<?php echo $this->getLayout()->createBlock(Magento\Framework\View\Element\Template::class)->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_product)->toHtml(); ?>
									</div>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach; ?>
			<?php } else { ?>
				<?php foreach ($_productCollection as $_product): ?>
					<li class="item product product-item">
					<div class="product-item-info clearfix<?php echo !$_product->isAvailable() ? ' sold-out' : ''; ?>" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
						<div class="indent product-hover-1">
							<div class="image-wrapper">
								<?php
								$hoverImage = $image_hover_status ? $_product->getHoverImage() : false;
								if ($hoverImage)
								{
									$hoverImageUrl = $this->helper(Magento\Catalog\Helper\Image::class)
													  ->init($_product, 'hover_image')
													  ->setImageFile($hoverImage)
													  ->getUrl();
									$productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>$hoverImageUrl));
								}
								else
								{
									$productImage = $block->getImage($_product, $imageDisplayArea, array('data-hover-image'=>null));
								}

								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								} ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php echo $productImage->toHtml(); ?>
								</a>
	                            <?php
	                                if($front_helper->isProductNew($_product) || $front_helper->isProductSale($_product) || $front_helper->isProductOnlyLeft($_product)){
	                                    echo '<div class="product-labels clearfix '.$labels_type.' '.(($front_helper->isProductNew($_product) && $front_helper->isProductSale($_product)) || ($front_helper->isProductNew($_product) && $front_helper->isProductOnlyLeft($_product)) ? ' two-items' : '').'">';
	                                        if($front_helper->isProductNew($_product) && $label_new) {
	                                            echo '<span class="label-new">'.__('new').'</span>';
	                                        }
	                                        if ($front_helper->isProductOnlyLeft($_product) && $label_sale) {
	                                            echo $front_helper->isProductOnlyLeft($_product);
	                                        }
	                                        elseif($front_helper->getProductSalePercent($_product) && $label_sale) {
	                                            echo $front_helper->getProductSalePercent($_product);
	                                        } elseif ($front_helper->isProductSale($_product) && $label_sale) {
	                                            echo '<span class="label-sale">'.__('sale').'</span>';
	                                        }
	                                    echo '</div>';
	                                }
	                            ?>
	                            <div class="hover-buttons">
		                            <?php if($lightbox_status && $lightbox_listing_status){ ?>
		                                <a href="<?php echo $productImage->getImageUrl();  ?>" class="lightbox-button"  data-toggle="lightbox" data-footer="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" title="<?php echo __('Lightbox'); ?>">
		                                    <i class="meigee-zoom"></i>
		                                </a>
		                            <?php } ?>		                            
                                    <?php if($compare_btn || $wishlist_btn){ ?>
                                        <div data-role="add-to-links" class="add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php } ?>	                            	
		                            <?php if($quickview_btn && $quickview_status) { ?>
		                                <a href="javascript: void(0);" data-quickview-url="<?php echo $block->getBaseUrl(); ?>weltpixel_quickview/catalog_product/view/id/<?php echo $block->escapeHtml($_product->getEntityId()); ?>" class="weltpixel-quickview"><i class="meigee-fa-eye"></i><span><?php /* @escapeNotVerified */ echo __('Quick view') ?></span></a>
		                            <?php } ?>		                            
		                            <?php if($cart_btn){ ?>
		                                <div class="product-action-wrapper">
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?php echo $block->escapeUrl($postParams['action']); ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @noEscape */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @noEscape */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @noEscape */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtmlAttr(__('Add to Cart')); ?>"
															class="action tocart btn btn-default btn-cart">
														<i class="meigee-cart"></i>
														<span><?php echo $block->escapeHtml(__('Add to Cart')) ?></span>
													</button>
												</form>
											<?php else: ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><i class="meigee-eye"></i><span><?php echo __('Read more') ?></span></a>
											<?php endif; ?>
		                                </div>
		                            <?php } ?>
	                            </div>
	                            <?php if (!$_product->isAvailable()): ?>
	                                <div class="sold-out-label">
	                                    <span><?php /* @escapeNotVerified */ echo __('Sold out') ?></span>
	                                </div>
	                            <?php endif; ?>
							</div>
							<div class="product details product-item-details">
	                            <?php if($product_name){
	                                $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
	                                <h4 class="product name product-item-name <?php echo $name_align; ?>">
	                                    <a class="product-item-link"
	                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
	                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
	                                    </a>
	                                </h4>
	                            <?php }
	                            if($stock_status != 4 && $stock_status != 2) {
	                                if ($_product->isAvailable()): ?>
	                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
	                                <?php else: ?>
	                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
	                               <?php endif;
	                            }
	
	                                echo $block->getReviewsSummaryHtml($_product, $templateType);
	                             ?>
	                            <div class="product-item-inner">
	                                 <?php if ($showDescription):?>
	                                    <div class="product description product-item-description">
	                                        <?php /* @noEscape */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
	                                        <a href="<?php echo $block->escapeUrl($_product->getProductUrl()) ?>" title="<?php /* @noEscape */ echo $_productNameStripped ?>"
	                                           class="action more"><?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Learn More')) ?></a>
	                                    </div>
	                                <?php endif; ?>
	                            </div>
	                            <div class="swatches-wrapper">
	                                <?php echo $block->getProductDetailsHtml($_product); ?>
	                            </div>
	                            <?php if($product_price){ ?>
	                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product); ?>
	                            <?php } ?>
	                            <?php echo $this->getLayout()->createBlock(Magento\Framework\View\Element\Template::class)->setTemplate("Magento_Catalog::product/product_timer.phtml")->setProduct($_product)->toHtml(); ?>
								</div>
							</div>
						</div>
					</li>
				<?php endforeach; ?>
			<?php } ?>
        </ol>
    </div>
	<div class="toolbar-bottom">
		<?php echo $block->getToolbarHtml() ?>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
   <script type="text/javascript">
require(['jquery'], function ($)
{

	jQuery(document).ready(function(){
		function listingBanner() {
			if(jQuery('.category-description .listing-banner').length){
				var mode = jQuery('.listing-banner').data('mode');
				var position = jQuery('.listing-banner').data('position');
				var rowPosition = jQuery('.listing-banner').data('rowPosition');
				banner1 = jQuery('.listing-banner');
				if(jQuery('.listing-banner-wrapper').length == 0) {
					banner = banner1.clone();
					banner = banner.wrap("<li class='item listing-banner-wrapper'></li>");
					banner.parent().hide();
					if(!jQuery('.category-description').find('.listing-banner-wrapper').length) {
						banner.parent().appendTo(jQuery('.category-description'));
					}
				}
				switch (mode){
					case 'grid':
						if(jQuery('.products.products-grid').length){
							banner.parent().show();
							jQuery('.products-grid').parents('.main-container').find('.category-description li.item').css('display', 'block');
							if (rowPosition == 1) {
								rowPosition = 2;
							}
							if (rowPosition) {
								columns=1;
								if (jQuery(document.body).width() >= 375 && jQuery(document.body).width() <= 767) {
									columns = 2;
								} else if (jQuery(document.body).width() < 375) {
									columns = 1;
								} else if (jQuery(document.body).width() >= 768 && jQuery(document.body).width() <= 1007) {
									columns = 3;
								} else if (jQuery(document.body).width() >= 1008) {
									if (jQuery('.products-grid').hasClass('eight-columns')) {
										columns = 8;
									} else if (jQuery('.products-grid').hasClass('seven-columns')) {
										columns = 7;
									} else if (jQuery('.products-grid').hasClass('six-columns')) {
										columns = 6;
									} else if (jQuery('.products-grid').hasClass('five-columns')) {
										columns = 5;
									} else if (jQuery('.products-grid').hasClass('four-columns')) {
										columns = 4;
									} else if (jQuery('.products-grid').hasClass('three-columns')) {
										columns = 3;
									} else if (jQuery('.products-grid').hasClass('two-columns')) {
										columns = 2;
									}
								}

								if (jQuery(document.body).width() >= 1008 && jQuery(document.body).width() <= 1331
									&& (columns == 8 || columns == 7 || columns == 6)
									&& (jQuery('.main-container').hasClass('col2-left-layout') || jQuery('.main-container').hasClass('col2-right-layout'))) {
										columns = 5;
								}

								if(jQuery('.products-grid').find('li.listing-banner-wrapper').length == 0) {
									jQuery('.products-grid li.item:nth-of-type(' + columns*(rowPosition-1) + ')').after(jQuery('.category-description .listing-banner-wrapper').addClass('row-banner'));
								}
							} else {
								if(jQuery('.products-grid li.listing-banner-wrapper').length == 0) {
									jQuery('.products-grid li.item:nth-of-type(' + (position-1) + ')').after(jQuery('.category-description .listing-banner-wrapper'));
								}
							}
						}
					break;
					case 'list':
						if(jQuery('.products.products-list').length){
							if(jQuery('.products-list li.listing-banner-wrapper').length == 0) {
								banner.parent().show();
								jQuery('.products-list').parents('.main-container').find('.category-description li.item').css('display', 'block');
								jQuery('.products-list li.item:nth-of-type(' + (position-1) + ')').after(jQuery('.listing-banner-wrapper'));
							}
						}
					break;
				}
			}
		}
		function moveListingBanner () {
		    if (jQuery('.products-grid .listing-banner-wrapper').length) {
		        rowPosition = jQuery('.products-grid .listing-banner-wrapper .listing-banner').data('rowPosition');
		        if (rowPosition) {
		            columns=1;
		            if (jQuery(document.body).width() >= 375 && jQuery(document.body).width() <= 767) {
		                columns = 2;
		            } else if (jQuery(document.body).width() < 375) {
		                columns = 1;
		            } else if (jQuery(document.body).width() >= 768 && jQuery(document.body).width() <= 1007) {
		                columns = 3;
		            } else if (jQuery(document.body).width() >= 1008) {
		                if (jQuery('.products-grid').hasClass('eight-columns')) {
		                    columns = 8;
		                } else if (jQuery('.products-grid').hasClass('seven-columns')) {
		                    columns = 7;
		                } else if (jQuery('.products-grid').hasClass('six-columns')) {
		                    columns = 6;
		                } else if (jQuery('.products-grid').hasClass('five-columns')) {
		                    columns = 5;
		                } else if (jQuery('.products-grid').hasClass('four-columns')) {
		                    columns = 4;
		                } else if (jQuery('.products-grid').hasClass('three-columns')) {
		                    columns = 3;
		                } else if (jQuery('.products-grid').hasClass('two-columns')) {
		                    columns = 2;
		                }
		            }

		            if (jQuery(document.body).width() >= 1008 && jQuery(document.body).width() <= 1331
		                && (columns == 8 || columns == 7 || columns == 6)
		                && (jQuery('.main-container').hasClass('col2-left-layout') || jQuery('.main-container').hasClass('col2-right-layout'))) {
		                    columns = 5;
		            }
		            banner = jQuery('.listing-banner-wrapper').remove();
		            jQuery('.products-grid li.item:not(.listing-banner-wrapper):nth-of-type(' + columns*(rowPosition-1) + ')').after(banner);
		        }
		    }
		}
		listingBanner();
	    jQuery(window).resize(function() {
	        moveListingBanner();
	    });
		
	    <?php if($listingCustomGrid == 1 ): ?>
            require(['jquery', 'meigeeCookies'], function ()
            {
                jQuery(window).bind('unload', function(e) {
                    console.log(e);
                    console.log(window.event);
                    var evt = e || window.event;
                    if (evt.clientX < 0 && evt.clientY < 0){
                        jQuery.removeCookie('barbourListingGridSwitcher', { path: '/' });
                    }
                });
                var listingGrid = jQuery.cookie('barbourListingGridSwitcher');
                var productLists = jQuery('.products.wrapper.products-grid');
                var classesProductLists = ["one-column", "two-columns", "three-columns", "four-columns", "five-columns", "six-columns", "seven-columns", "eight-columns"];
                /*function listingGridCookie(){
                    jQuery.cookie('barbourListingGridSwitcher', '<?php echo $grid_columns ?>', {
                        expires: null,
                        path: '/'
                    });
                }*/
                function listingGridSwitch(){
                    jQuery.each(classesProductLists, function(i, v){
                        jQuery(productLists).removeClass(v);
                    });
                    jQuery(productLists).addClass(jQuery.cookie('barbourListingGridSwitcher'));
                    listingBanner();
                    moveListingBanner();
                }
                /*if(!(listingGrid)){
                    jQuery.cookie('barbourListingGridSwitcher', '<?php echo $grid_columns ?>', {
                        expires: null,
                        path: '/'
                    });
                }*/

                jQuery('.modes span.item').on('click', function(){
                    jQuery('.product-items .item').removeClass('hovered');
                    if (!jQuery(this).hasClass('current')) {
                        jQuery('.toolbar .modes span.item').removeClass('current');
                        jQuery(this).addClass('current');
                        jQuery.removeCookie('barbourListingGridSwitcher', null);
                        jQuery.cookie('barbourListingGridSwitcher', jQuery(this).data('grid-swither'), {
                            expires: null,
                            domain: window.location.host,
                            path: '/'
                        });
                        listingGridSwitch();
                    }
                });


            });
        <?php endif; ?>
	});
});

</script>
<?php endif; ?>
