<?php
/**
 * Webkul Software
 *
 * @category    Webkul
 * @package     Webkul_OutOfStockNotification
 * @author      Webkul
 * @copyright   Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license     https://store.webkul.com/license.html
 */
?>

<div class="wk-loading-mask-outer wk-display-none">
        <div class="wk-loader"></div>
    </div>
    <div class="wk-container wk-display-none">
        <div class="wk-oosn-container">
            <div class="wk-oosn-notificationcontainer">
                <div class="wk-loading-mask wk-display-none">
                    <div class="wk-loader"></div>
                </div>
                <div id="wk-notification-container">
                    <div class="wk-oosn-emailBox" data-bind="scope: 'section'">
                        <input type="text" name='email' id="oosn_email" placeholder="<?=$block->escapeHtml(__("Enter Your Email Id")) ?>" data-bind="value: customer().email" />
                    </div>
                    <button type="button" title="<?= $block->escapeHtml(__("Notify Me")) ?>" class="action primary tocart" id="wk-oosn-button">
                        <span><?=$block->escapeHtml(__("Notify Me")); ?></span>
                    </button>
                </div>
            </div>
        </div>
        <div id="wk-oosn-warning" class="message"></div>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "section": {
                        "component": "Webkul_OutOfStockNotification/js/section"
                    }
                }
            }
        }
    }
</script>
<!-- 24 | WARNING | Unescaped output detected.
 26 | WARNING | Unescaped output detected.
 27 | WARNING | Unescaped output detected. -->
