<?php
/**
 * Webkul Software
 *
 * @category    Webkul
 * @package     Webkul_OutOfStockNotification
 * @author      Webkul
 * @copyright   Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license     https://store.webkul.com/license.html
 */

$allowedTypes = ['simple', 'configurable', 'virtual', 'downloadable'];
$product = $block->getProductId();
$productModal = $block->getProduct();
$productId = $product['id'];
$productType = $product['type'];

if (in_array($productType, $allowedTypes)) {
    $stockStatus = $productModal->isAvailable();
    $failureMsg = __("Please enter a valid email");
    $blankMsg = __("No email found");

    $customerEmail = $block->getCustomerEmail();
    $fileUrl = $block->getViewFileUrl('images/loader.gif');
    $action = $block->getUrl('outofstocknotification/product/addcustomer');
    $actionConfig = $block->getUrl('outofstocknotification/product/configproduct');


    if ($productType == 'configurable') {
        $stockStatus = $product['stock'];
        $outOfStockAssociates = $product['oosn_associates'];
        $outOfStockAssociatesString = implode(",", $outOfStockAssociates);
        if (!empty($outOfStockAssociatesString)) {
            $title = __("Get Notified When Other Options (%1) Are Available !!", $outOfStockAssociatesString);
            ?>
            <select  id="associate-select" class="" aria-required="true">
                    <option value="<?=$block->escapeHtml($productId)?>">All out of stock options</option> 
                    <?php
                    
                    if (is_array($outOfStockAssociates) || is_object($outOfStockAssociates)) {
                        foreach ($outOfStockAssociates as $associateId => $assciate) {
                            ?><option value="<?=$block->escapeHtml($associateId)?>"><?=$block->escapeHtml($assciate)?></option><?php
                        }}
        } else {
            $title = __("Get Notified When Product Is In stock !!");
        }

    } else {
        $title = __("Get Notified When Product Is In stock !!");

    }
    ?>
    <input type="hidden" name="productId" value="<?= $block->escapeHtml($productId); ?>">
    <?php
            $optionElements = [
                'button' => '#wk-oosn-button',
                'loader' => '.wk-loading-mask',
                'email'    => 'email',
                'productId' => $productId,
                'stockStatus' => $stockStatus,
                'action' => $action,
                'productType' => $productType,
                'actionConfig' => $actionConfig,
                'form' => '.notificationForm',
                'failureMsg' => $failureMsg,
                'blankMsg' => $blankMsg,
                'container' => '.wk-oosn-notificationcontainer',
                'warning' => '#wk-oosn-warning',
                'title' =>  $title
            ];
            $serializedData = $block->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($optionElements);
            ?>
    <script type="text/x-magento-init">
    {
    "*":{
            "notifyMe":<?= /* @noEscape */  $serializedData; ?>
        }
    }
    </script>

<?php } ?>
