<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

$meigee_helper = $this->helper('\Meigee\Barbour\Helper\BarbourGeneral');
$login_link = $meigee_helper->getCustomThemeOptionCnf('barbour_toplinks', 'toplinks_login');
$register_link = $meigee_helper->getCustomThemeOptionCnf('barbour_toplinks', 'toplinks_register');
?>
<?php if(!$login_link){ ?>
	<?php echo $this->getChildHtml("authorization-link-login"); ?>
	<?php echo $this->getChildHtml("authorization-link-login-mobile"); ?>
<?php } ?>
<?php if(!$register_link){ ?>
	<?php echo $this->getChildHtml("register-link"); ?>
<?php } ?>