<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */

?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) : ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name) : ?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     data-role="collapsible" id="tab-label-<?php echo $block->escapeHtmlAttr($alias); ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="trigger"
                       href="#<?php echo $block->escapeUrl($alias); ?>"
                       id="tab-label-<?php echo $block->escapeHtmlAttr($alias); ?>-title">
                        <?php /* @noEscape */ echo $label; ?>
                    </a>
                </div>
                <div class="data item content" aria-labelledby="tab-label-<?php echo $block->escapeHtmlAttr($alias); ?>-title" id="<?php echo $block->escapeHtmlAttr($alias); ?>" data-role="content">
                    <?php /* @noEscape */ echo $html; ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
